/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Address } from './Address.ts'

export const customerParamsStatusEnum = {
  placed: 'placed',
  approved: 'approved',
  delivered: 'delivered',
} as const

export type CustomerParamsStatusEnumKey = (typeof customerParamsStatusEnum)[keyof typeof customerParamsStatusEnum]

export type CustomerParamsStatusEnum = CustomerParamsStatusEnumKey

export type Customer = {
  /**
   * @example 100000
   * @type integer | undefined
   */
  id?: number
  /**
   * @type object | undefined
   */
  params?: {
    /**
     * @description Order Status
     * @example approved
     * @type string
     */
    status: CustomerParamsStatusEnumKey
    /**
     * @type string
     */
    type: string
  }
  /**
   * @example fehguy
   * @type string | undefined
   */
  username?: string
  /**
   * @type array | undefined
   */
  address?: Address[]
}
