/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cat } from './Cat.ts'
import type { Category } from './Category.ts'
import type { Dog } from './Dog.ts'
import type { Tag } from './Tag.ts'

export const petTypeEnum = {
  dog: 'dog',
  cat: 'cat',
} as const

export type PetTypeEnumKey = (typeof petTypeEnum)[keyof typeof petTypeEnum]

export const petStatusEnum = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type PetStatusEnumKey = (typeof petStatusEnum)[keyof typeof petStatusEnum]

export type Pet = (
  | (Dog & {
      /**
       * @type string
       */
      readonly type: 'dog'
    })
  | (Cat & {
      /**
       * @type string
       */
      readonly type: 'cat'
    })
) & {
  /**
   * @example 10
   * @type integer | undefined
   */
  id?: number
  /**
   * @type string
   */
  readonly type: PetTypeEnumKey
  /**
   * @example doggie
   * @type string
   */
  name: string
  category?: Category
  /**
   * @type array
   */
  photoUrls: string[]
  /**
   * @type array | undefined
   */
  readonly tags?: Tag[]
  /**
   * @description pet status in the store
   * @type string | undefined
   */
  status?: PetStatusEnumKey
}
