/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cat } from './Cat.ts'
import type { Category } from './Category.ts'
import type { Dog } from './Dog.ts'
import type { Tag } from './Tag.ts'

export const statusEnum = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type StatusEnumKey = (typeof statusEnum)[keyof typeof statusEnum]

export type Pet =
  | (Dog & {
      id?: number
      readonly type: 'dog'
      name: string
      category?: Category
      photoUrls: string[]
      readonly tags?: Tag[]
      /**
       * @description pet status in the store
       */
      status?: StatusEnumKey
    })
  | (Cat & {
      id?: number
      readonly type: 'cat'
      name: string
      category?: Category
      photoUrls: string[]
      readonly tags?: Tag[]
      /**
       * @description pet status in the store
       */
      status?: StatusEnumKey
    })
