openapi: 3.0.0
info:
  title: allOf maxLength Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    PhoneNumber:
      type: string
      pattern: '^(\+\d{1,3}[-\s]?)?\(?(?:\d{1,4})\)?[-\s]?\d{1,4}[-\s]?\d{1,9}$'
    PhoneWithMaxLength:
      allOf:
        - $ref: '#/components/schemas/PhoneNumber'
        - maxLength: 15
    PhoneWithMaxLengthExplicit:
      allOf:
        - $ref: '#/components/schemas/PhoneNumber'
        - type: string
          maxLength: 15
