openapi: 3.1.0
info:
  title: Test anyOf with binary
  version: 1.0.0
paths: {}
components:
  schemas:
    OptionalFile:
      type: object
      properties:
        file:
          anyOf:
            - type: string
              format: binary
            - type: null
      required:
        - file
