
definitions:
  enumVarNames.Type:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - Pending
    - Received
  enumNames.Type:
    enum:
    - 0
    - 1
    x-enumNames:
      - Pending
      - Received
  enum.String:
    type: string
    enum:
      - created_at
      - description
  enum.InObject:
    type: object
    properties:
      reason:
        type: string
        enum:
          - created_at
          - description
  enum.Items:
    type: array
    minItems: 1
    uniqueItems: true
    items:
      type: string
      enum:
        - created_at
        - description
swagger: "2.0"
info:
  title: test
  version: "1.0.0"
paths:
  /var-names:
    get:
      consumes:
      - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/enumVarNames.Type'
  /names:
    get:
      consumes:
      - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/enumNames.Type'
