export { ClackAdapter } from './ClackAdapter.ts'
export { canUseTTY, isCIEnvironment, isGitHubActions } from './envDetection.ts'
export { GitHubActionsAdapter } from './GitHubActionsAdapter.ts'
export type { AdapterType } from './LoggerAdapterFactory.ts'
export { LoggerAdapterFactory } from './LoggerAdapterFactory.ts'
export { PlainAdapter } from './PlainAdapter.ts'
export type { LoggerAdapter, LoggerAdapterOptions } from './types.ts'
