/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pet } from "./Pet.ts";

export const findPetsByStatusQueryParamsStatusEnum = {
    available: "available",
    pending: "pending",
    sold: "sold"
} as const;

export type FindPetsByStatusQueryParamsStatusEnumKey = (typeof findPetsByStatusQueryParamsStatusEnum)[keyof typeof findPetsByStatusQueryParamsStatusEnum];

/**
 * @type object
*/
export type FindPetsByStatusQueryParams = {
    /**
     * @description Status values that need to be considered for filter
     * @default "available"
     * @type string | undefined
    */
    status?: FindPetsByStatusQueryParamsStatusEnumKey;
};

/**
 * @description successful operation
 * @type array
*/
export type FindPetsByStatus200 = Pet[];

/**
 * @description Invalid status value
 * @type any
*/
export type FindPetsByStatus400 = any;

export type FindPetsByStatusQueryResponse = FindPetsByStatus200;

/**
 * @type object
*/
export type FindPetsByStatusQuery = {
    Response: FindPetsByStatus200;
    QueryParams: FindPetsByStatusQueryParams;
    Errors: FindPetsByStatus400;
};