/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type object
 */
export type Pet = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
}
