/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface PetNotFound {
  /**
   * @type integer | undefined
   */
  code?: number
  /**
   * @type string | undefined
   */
  message?: string
}
