/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import fetch from 'axios'
import useSWRMutation from 'swr/mutation'
import type { RequestConfig, ResponseErrorConfig } from 'axios'
import type { ClientPostImportPath } from './clientPostImportPath'
import type { SWRMutationConfiguration } from 'swr/mutation'

export const updatePetWithForm = () => [{ url: '/pet/:petId' }] as const

export type ClientPostImportPathMutationKey = ReturnType<typeof updatePetWithForm>

/**
 * @summary Updates a pet in the store with form data
 * {@link /pet/:petId}
 */
export async function clientPostImportPath(
  petId: ClientPostImportPath['petId'],
  params?: ClientPostImportPath,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ClientPostImportPath, ResponseErrorConfig<ClientPostImportPath>, unknown>({
    method: 'POST',
    url: `/pet/${petId}`,
    params,
    ...requestConfig,
  })
  return res.data
}

/**
 * @summary Updates a pet in the store with form data
 * {@link /pet/:petId}
 */
export function useClientPostImportPath(
  petId: ClientPostImportPath['petId'],
  params?: ClientPostImportPath,
  options: {
    mutation?: SWRMutationConfiguration<ClientPostImportPath, ResponseErrorConfig<ClientPostImportPath>, ClientPostImportPathMutationKey | null, never> & {
      throwOnError?: boolean
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
    shouldFetch?: boolean
  } = {},
) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {}
  const mutationKey = updatePetWithForm()

  return useSWRMutation<ClientPostImportPath, ResponseErrorConfig<ClientPostImportPath>, ClientPostImportPathMutationKey | null>(
    shouldFetch ? mutationKey : null,
    async (_url) => {
      return clientPostImportPath(petId, params, config)
    },
    mutationOptions,
  )
}
