/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const PetStatus = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type PetStatusKey = (typeof PetStatus)[keyof typeof PetStatus]
