/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Pet = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type array | undefined
   */
  tags?: string[]
}
