packages:
  - packages/*
  - docs
  - examples/*
  - tests/**

catalog:
  "@types/node": ^20.19.27
  "@kubb/fabric-core": 0.9.2
  "@kubb/react-fabric": 0.9.2
  "@size-limit/file": ^11.2.0
  "size-limit": ^11.2.0
  p-limit: ^7.2.0
  remeda: ^2.33.1
  tsdown: ^0.18.4
  typescript: ^5.9.3
