packages:
  - packages/*
  - docs
  - examples/*
  - e2e
catalogs:
  react18:
    '@types/react': ^18.3.24
    '@types/react-dom': ^18.3.7
    '@types/react-reconciler': 0.28.9
    react: ^18.3.1
    react-dom: ^18.3.1
    react-reconciler: 0.29.2
  react19:
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.7
    '@types/react-reconciler': 0.32.0
    react: ^19.1.1
    react-dom: ^19.1.1
    react-reconciler: 0.32.0
catalog:
  '@types/react': ^18.3.24
  '@types/node': ^20.19.11
  '@types/react-dom': ^18.3.7
  '@types/react-reconciler': 0.32.0
  react: ^18.3.1
  react-dom: ^18.3.1
  react-reconciler: 0.32.0
  p-limit: ^7.1.0
  tsdown: ^0.14.2
  typescript: ^5.9.2
  remeda: ^2.30.0
