packages:
  - packages/*
  - docs
  - examples/*
  - e2e

catalog:
  '@types/node': ^20.19.24
  '@kubb/fabric-core': 0.3.1
  '@kubb/react-fabric': 0.3.1
  '@size-limit/file': ^11.2.0
  'size-limit': ^11.2.0
  p-limit: ^7.2.0
  remeda: ^2.32.0
  tsdown: ^0.16.0
  typescript: ^5.9.3
