packages:
  - packages/*
  - internals/*

catalog:
  "@types/node": ^22.19.17
  "@types/react": ^19.2.14
  "@types/react-reconciler": 0.32.0
  "@size-limit/file": ^11.2.0
  "size-limit": ^11.2.0
  "tinyexec": ^1.1.1
  react: 19.2.3
  react-reconciler: 0.33.0
  p-limit: ^7.3.0
  remeda: ^2.33.7
  tsdown: ^0.21.9
  typescript: ^6.0.2
