packages:
  - packages/*
  - internals/*
  - examples/*
  - tests/**

catalog:
  '@kubb/fabric-core': 0.14.0
  '@kubb/react-fabric': 0.14.0
  '@size-limit/file': ^11.2.0
  '@types/node': ^20.19.41
  p-limit: ^7.3.0
  remeda: ^2.37.0
  size-limit: ^11.2.0
  tinyexec: ^1.2.4
  tsdown: ^0.21.10
  typescript: ^5.9.3
