packages:
  - packages/*
  - examples/*
  - tests/**

catalog:
  "@types/node": ^20.19.32
  "@kubb/fabric-core": 0.12.10
  "@kubb/react-fabric": 0.12.10
  "@size-limit/file": ^11.2.0
  "size-limit": ^11.2.0
  p-limit: ^7.3.0
  remeda: ^2.33.5
  # cannot upgrade to 0.20.3 because of breaking changes with react-fabric types
  tsdown: ^0.19.0
  typescript: ^5.9.3
