packages:
  - packages/*
  - examples/*
  - tests/**

catalog:
  "@types/node": ^20.19.30
  "@kubb/fabric-core": 0.11.8
  "@kubb/react-fabric": 0.11.8
  "@size-limit/file": ^11.2.0
  "size-limit": ^11.2.0
  p-limit: ^7.2.0
  remeda: ^2.33.4
  tsdown: ^0.20.1
  typescript: ^5.9.3
