/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ShowPetByIdPathPetId, ShowPetByIdResponse } from './ShowPetById'

export function showPetById(petId: ShowPetByIdPathPetId, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<ShowPetByIdResponse> {
  return cy
    .request<ShowPetByIdResponse>({
      method: 'GET',
      url: `/pets/${petId}`,
      ...options,
    })
    .then((res) => res.body)
}
