/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

/**
 * @type {string}
 */
export const getPetsHeaderXRequestIdSchema = z.string()

/**
 * @type {string | undefined}
 */
export const getPetsHeaderXCorrelationIdSchema = z.string().optional()

/**
 * @type {object}
 */
export const getPetsStatus200Schema = z.object({})
