/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, CreateBaseQueryOptions, CreateQueryResult } from '@tanstack/react-query'
import type { FindByTagsWithCustomQueryKey } from './findByTagsWithCustomQueryKey'
import { queryOptions, createQuery } from '@tanstack/react-query'
import { findByTagsWithCustomQueryKey } from './findByTagsWithCustomQueryKey'

export const findPetsByTags = (params?: FindByTagsWithCustomQueryKey) => ['test', { url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type FindByTagsWithCustomQueryKeyQueryKey = ReturnType<typeof findPetsByTags>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function findByTagsWithCustomQueryKey(
  headers: FindByTagsWithCustomQueryKey,
  params?: FindByTagsWithCustomQueryKey,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindByTagsWithCustomQueryKey, ResponseErrorConfig<FindByTagsWithCustomQueryKey>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return findByTagsWithCustomQueryKey.parse(res.data)
}

export function findByTagsWithCustomQueryKeyQueryOptions(
  headers: FindByTagsWithCustomQueryKey,
  params?: FindByTagsWithCustomQueryKey,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByTags(params)
  return queryOptions<FindByTagsWithCustomQueryKey, ResponseErrorConfig<FindByTagsWithCustomQueryKey>, FindByTagsWithCustomQueryKey, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return findByTagsWithCustomQueryKey(headers, params, config)
    },
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function createFindByTagsWithCustomQueryKey<
  TData = FindByTagsWithCustomQueryKey,
  TQueryData = FindByTagsWithCustomQueryKey,
  TQueryKey extends QueryKey = FindByTagsWithCustomQueryKeyQueryKey,
>(
  headers: FindByTagsWithCustomQueryKey,
  params?: FindByTagsWithCustomQueryKey,
  options: {
    query?: Partial<CreateBaseQueryOptions<FindByTagsWithCustomQueryKey, ResponseErrorConfig<FindByTagsWithCustomQueryKey>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? findPetsByTags(params)

  const query = createQuery(
    {
      ...findByTagsWithCustomQueryKeyQueryOptions(headers, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as CreateBaseQueryOptions,
    queryClient,
  ) as CreateQueryResult<TData, ResponseErrorConfig<FindByTagsWithCustomQueryKey>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
