/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, CreateBaseQueryOptions, CreateQueryResult } from '@tanstack/svelte-query'
import type { FindByTags } from './findByTags'
import { queryOptions, createQuery } from '@tanstack/svelte-query'
import { findByTags } from './findByTags'

export const findPetsByTags = (params?: FindByTags) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type FindByTagsQueryKey = ReturnType<typeof findPetsByTags>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function findByTags(headers: FindByTags, params?: FindByTags, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindByTags, ResponseErrorConfig<FindByTags>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return findByTags.parse(res.data)
}

export function findByTagsQueryOptions(headers: FindByTags, params?: FindByTags, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = findPetsByTags(params)
  return queryOptions<FindByTags, ResponseErrorConfig<FindByTags>, FindByTags, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return findByTags(headers, params, config)
    },
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function createFindByTags<TData = FindByTags, TQueryData = FindByTags, TQueryKey extends QueryKey = FindByTagsQueryKey>(
  headers: FindByTags,
  params?: FindByTags,
  options: {
    query?: Partial<CreateBaseQueryOptions<FindByTags, ResponseErrorConfig<FindByTags>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? findPetsByTags(params)

  const query = createQuery(
    {
      ...findByTagsQueryOptions(headers, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as CreateBaseQueryOptions,
    queryClient,
  ) as CreateQueryResult<TData, ResponseErrorConfig<FindByTags>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
