/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseBaseQueryOptions, UseQueryResult } from '@tanstack/svelte-query'
import type { ClientDataReturnTypeFull } from './clientDataReturnTypeFull'
import { queryOptions, useQuery } from '@tanstack/svelte-query'
import { clientDataReturnTypeFull } from './clientDataReturnTypeFull'

export const findPetsByTags = (params?: ClientDataReturnTypeFull) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type ClientDataReturnTypeFullQueryKey = ReturnType<typeof findPetsByTags>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function clientDataReturnTypeFull(
  headers: ClientDataReturnTypeFull,
  params?: ClientDataReturnTypeFull,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ClientDataReturnTypeFull, ResponseErrorConfig<ClientDataReturnTypeFull>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return { ...res, data: clientDataReturnTypeFull.parse(res.data) }
}

export function clientDataReturnTypeFullQueryOptions(
  headers: ClientDataReturnTypeFull,
  params?: ClientDataReturnTypeFull,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByTags(params)
  return queryOptions<
    ResponseConfig<ClientDataReturnTypeFull>,
    ResponseErrorConfig<ClientDataReturnTypeFull>,
    ResponseConfig<ClientDataReturnTypeFull>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return clientDataReturnTypeFull(headers, params, config)
    },
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function createClientDataReturnTypeFull<
  TData = ResponseConfig<ClientDataReturnTypeFull>,
  TQueryData = ResponseConfig<ClientDataReturnTypeFull>,
  TQueryKey extends QueryKey = ClientDataReturnTypeFullQueryKey,
>(
  headers: ClientDataReturnTypeFull,
  params?: ClientDataReturnTypeFull,
  options: {
    query?: Partial<
      UseBaseQueryOptions<ResponseConfig<ClientDataReturnTypeFull>, ResponseErrorConfig<ClientDataReturnTypeFull>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? findPetsByTags(params)

  const query = useQuery(
    () => ({
      ...(clientDataReturnTypeFullQueryOptions(headers, params, config) as unknown as UseBaseQueryOptions),
      queryKey,
      initialData: null,
      ...(queryOptions as unknown as Omit<UseBaseQueryOptions, 'queryKey'>),
    }),
    queryClient ? () => queryClient : undefined,
  ) as UseQueryResult<TData, ResponseErrorConfig<ClientDataReturnTypeFull>> & { queryKey: TQueryKey }

  return query
}
