/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type _4E2Bce4 = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    email: string;
    /**
     * @type string | undefined
    */
    name?: string;
};