/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pet } from '../Pet.ts'

/**
 * @default available
 */
export type FindPetsByStatusQueryStatus = 'available' | 'pending' | 'sold'

/**
 * @description successful operation
 */
export type FindPetsByStatusStatus200 = Pet[]

/**
 * @description Invalid status value
 */
export type FindPetsByStatusStatus400 = any

export interface FindPetsByStatusRequestConfig {
  data?: never
  pathParams?: never
  queryParams?: {
    status?: FindPetsByStatusQueryStatus
  }
  headerParams?: never
  url: '/pet/findByStatus'
}

export interface FindPetsByStatusResponses {
  '200': FindPetsByStatusStatus200
  '400': FindPetsByStatusStatus400
}

/**
 * @description Union of all possible responses
 */
export type FindPetsByStatusResponse = FindPetsByStatusStatus200 | FindPetsByStatusStatus400
