components:
  schemas:
    enumVarNames.Type:
      enum:
      - 0
      - 1
      type: integer
      x-enum-varnames:
      - Pending
      - Received
    enumNames.Type:
      enum:
      - 0
      - 1
      x-enumNames:
        - Pending
        - Received
    enum.String:
      type: string
      enum:
        - created_at
        - description
        - FILE.UPLOADED
        - FILE.DOWNLOADED
    enum.NullableMember:
      type: string
      enum:
        - first
        - second
        - null
    enum.NullableType:
      type:
        - string
        - "null"
      enum:
        - first
        - second
    enum.InObject:
      type: object
      properties:
        reason:
          type: string
          enum:
            - created_at
            - description
    enum.AllOf:
      type: object
      properties:
        reason:
          allOf:
            - type: string
              enum:
                - created_at
                - description

    enum.Array:
      type: array
      items:
        type: string
        enum:
          - "NW"
          - "NE"
          - "SW"
          - "SE"
        description: Wind direction

    enum.Items:
      type: array
      minItems: 1
      uniqueItems: true
      items:
        type: string
        enum:
          - created_at
          - description

openapi: "3.1.0"
info:
  title: test
  version: "1.0.0"
paths:
  /var-names:
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/definitions/enumVarNames.Type'
  /names:
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/definitions/enumNames.Type'
