openapi: 3.0.0
info:
  title: Snake Case Params Test
  version: 1.0.0
paths:
  /test/{test_id}:
    post:
      operationId: performActionTesting
      parameters:
        - name: test_id
          in: path
          required: true
          schema:
            type: string
        - name: secondary_testing_param
          in: query
          required: false
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                test_data:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
