/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetOrderByIdPathOrderId, GetOrderByIdResponse } from "../types/GetOrderById.ts";

export function getOrderById(orderId: GetOrderByIdPathOrderId, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<GetOrderByIdResponse> {
  return cy.request<GetOrderByIdResponse>({
    method: 'GET',
    url: `/store/order/${orderId}`,
    ...options
  }).then((res) => res.body)
}