/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

/**
 * @type {string}
 */
export const deletePetPathPetIdSchema = z.string()

/**
 * @type {void}
 */
export const deletePetStatus204Schema = z.void()
