/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod/mini";
import { categorySchema } from "./categorySchema.ts";
import { tagSchema } from "./tagSchema.ts";

export const addPetRequestSchema = z.object({
  id: z.optional(z.int()),
  name: z.string(),
  category: z.optional(categorySchema),
  photoUrls: z.array(z.string()),
  tags: z.optional(z.array(tagSchema)),
  status: z.optional(z.enum(["available", "pending", "sold"])),
});
