/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'
import { petSchema } from './petSchema.ts'
import { postPetRequestSchema } from './postPetRequestSchema.ts'

/**
 * @description Successful operation
 */
export const addPet200Schema = z.lazy(() => petSchema)

/**
 * @description Pet not found
 */
export const addPet405Schema = z.object({
  code: z.optional(z.int()),
  message: z.optional(z.string()),
})

/**
 * @description Create a new pet in the store
 */
export const addPetMutationRequestSchema = z.lazy(() => postPetRequestSchema)

export const addPetMutationResponseSchema = z.lazy(() => addPet200Schema)
