/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { addPetRequestSchema } from "./addPetRequestSchema.ts";
import { petSchema } from "./petSchema.ts";
import { z } from "zod/mini";

/**
 * @description Successful operation
 */
export const addPet200Schema = z.lazy(() => petSchema);

/**
 * @description Pet not found
 */
export const addPet405Schema = z.object({
  code: z.optional(z.int()),
  message: z.optional(z.string()),
});

/**
 * @description Create a new pet in the store
 */
export const addPetMutationRequestSchema = z.lazy(() => addPetRequestSchema);

export const addPetMutationResponseSchema = z.lazy(() => addPet200Schema);
