/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'
import { petNotFoundSchema } from './petNotFoundSchema.ts'

export const createPetsPathParamsSchema = z.object({
  uuid: z.string(),
})

export const createPetsQueryParamsSchema = z.optional(
  z.object({
    offset: z.optional(z.int()),
  }),
)

export const createPetsHeaderParamsSchema = z.object({
  'X-EXAMPLE': z.enum(['ONE', 'TWO', 'THREE']),
})

/**
 * @description Null response
 */
export const createPetsStatus201Schema = z.any()

/**
 * @description unexpected error
 */
export const createPetsStatusErrorSchema = z.lazy(() => petNotFoundSchema)

export const createPetsRequestDataSchema = z.object({
  name: z.string(),
  tag: z.string(),
})

export const createPetsResponseDataSchema = z.lazy(() => createPetsStatus201Schema)
