/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from "./userSchema.ts";
import { z } from "zod/mini";

/**
 * @description successful operation
 */
export const createUserErrorSchema = z.lazy(() => userSchema);

/**
 * @description Created user object
 */
export const createUserMutationRequestSchema = z.lazy(() => userSchema);

export const createUserMutationResponseSchema = z.any();
