/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/mini";

export const deleteOrderPathParamsSchema = z.object({
    "orderId": z.int()
    })

export type DeleteOrderPathParamsSchema = z.infer<typeof deleteOrderPathParamsSchema>

/**
 * @description Invalid ID supplied
 */
export const deleteOrder400Schema = z.any()

export type DeleteOrder400Schema = z.infer<typeof deleteOrder400Schema>

/**
 * @description Order not found
 */
export const deleteOrder404Schema = z.any()

export type DeleteOrder404Schema = z.infer<typeof deleteOrder404Schema>

export const deleteOrderMutationResponseSchema = z.any()

export type DeleteOrderMutationResponseSchema = z.infer<typeof deleteOrderMutationResponseSchema>