/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'

export const deleteOrderPathParamsSchema = z.object({
  orderId: z.coerce.bigint(),
})

/**
 * @description Invalid ID supplied
 */
export const deleteOrder400Schema = z.any()

/**
 * @description Order not found
 */
export const deleteOrder404Schema = z.any()

export const deleteOrderMutationResponseSchema = z.any()
