/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'

export const deletePetPathParamsSchema = z.object({
  petId: z.coerce.bigint(),
})

export const deletePetHeaderParamsSchema = z.optional(
  z.object({
    api_key: z.optional(z.string()),
  }),
)

/**
 * @description Invalid pet value
 */
export const deletePet400Schema = z.any()

export const deletePetMutationResponseSchema = z.any()
