/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'

export const deletePetPathParamsSchema = z.object({
  petId: z.int(),
})

export const deletePetHeaderParamsSchema = z.optional(
  z.object({
    api_key: z.optional(z.string()),
  }),
)

export const deletePet400Schema = z.any()

export const deletePetMutationResponseSchema = z.any()

export const deletePetMutationSchema = z.object({
  Response: z.any(),
  PathParams: deletePetPathParamsSchema,
  HeaderParams: deletePetHeaderParamsSchema,
  Errors: deletePet400Schema,
})
