/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'
import { petSchema } from './petSchema.ts'

export const findPetsByTagsQueryParamsSchema = z.optional(
  z.object({
    tags: z.optional(z.array(z.string())),
    page: z.optional(z.string()),
    pageSize: z.optional(z.string()),
  }),
)

export const findPetsByTagsHeaderParamsSchema = z.object({
  'X-EXAMPLE': z.enum(['ONE', 'TWO', 'THREE']),
})

/**
 * @description successful operation
 */
export const findPetsByTagsStatus200Schema = z.array(z.lazy(() => petSchema))

/**
 * @description Invalid tag value
 */
export const findPetsByTagsStatus400Schema = z.any()

export const findPetsByTagsResponseDataSchema = z.lazy(() => findPetsByTagsStatus200Schema)
