/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { petSchema } from "./petSchema.ts";
import { z } from "zod/mini";

export const findPetsByTagsQueryParamsSchema = z.optional(
  z.object({
    tags: z.optional(z.array(z.string())),
    page: z.optional(z.string()),
    pageSize: z.optional(z.string()),
  }),
);

export const findPetsByTagsHeaderParamsSchema = z.object({
  "X-EXAMPLE": z.enum(["ONE", "TWO", "THREE"]),
});

/**
 * @description successful operation
 */
export const findPetsByTags200Schema = z.array(z.lazy(() => petSchema));

/**
 * @description Invalid tag value
 */
export const findPetsByTags400Schema = z.any();

export const findPetsByTagsQueryResponseSchema = z.lazy(
  () => findPetsByTags200Schema,
);
