/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'

/**
 * @description successful operation
 */
export const getInventoryStatus200Schema = z.object({})

export const getInventoryResponseDataSchema = z.lazy(() => getInventoryStatus200Schema)
