/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod/mini";

/**
 * @description successful operation
 */
export const getInventory200Schema = z.object({});

export const getInventoryQueryResponseSchema = z.lazy(
  () => getInventory200Schema,
);
