/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod/mini";
import { petNotFoundSchema } from "./petNotFoundSchema.ts";

export const getThingsQueryParamsSchema = z.optional(
  z.object({
    limit: z._default(
      z.optional(z.int().check(z.minimum(1), z.maximum(100))),
      100,
    ),
    skip: z._default(z.optional(z.int().check(z.minimum(0))), 0),
  }),
);

/**
 * @description Null response
 */
export const getThings201Schema = z.any();

/**
 * @description unexpected error
 */
export const getThingsErrorSchema = petNotFoundSchema;

export const getThingsQueryResponseSchema = getThings201Schema;

export const getThingsQuerySchema = z.object({
  Response: getThings201Schema,
  QueryParams: getThingsQueryParamsSchema,
  Errors: getThingsErrorSchema,
});
