/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'
import { petNotFoundSchema } from './petNotFoundSchema.ts'

export const getThingsQueryParamsSchema = z.object({
  limit: z.int().check(z.minimum(1), z.maximum(100)),
  skip: z.int().check(z.minimum(0)),
})

/**
 * @description Null response
 */
export const getThingsStatus201Schema = z.any()

/**
 * @description unexpected error
 */
export const getThingsStatusErrorSchema = z.lazy(() => petNotFoundSchema)

export const getThingsResponseDataSchema = z.lazy(() => getThingsStatus201Schema)
