/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { petNotFoundSchema } from "./petNotFoundSchema.ts";
import { z } from "zod/mini";

export const getThingsQueryParamsSchema = z.object({
    "limit": z.int().check(z.minimum(1), z.maximum(100)),
"skip": z.int().check(z.minimum(0))
    })

export type GetThingsQueryParamsSchema = z.infer<typeof getThingsQueryParamsSchema>

/**
 * @description Null response
 */
export const getThings201Schema = z.any()

export type GetThings201Schema = z.infer<typeof getThings201Schema>

/**
 * @description unexpected error
 */
export const getThingsErrorSchema = z.lazy(() => petNotFoundSchema)

export type GetThingsErrorSchema = z.infer<typeof getThingsErrorSchema>

export const getThingsQueryResponseSchema = z.lazy(() => getThings201Schema)

export type GetThingsQueryResponseSchema = z.infer<typeof getThingsQueryResponseSchema>