/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'

export const loginUserQueryParamsSchema = z.optional(
  z.object({
    username: z.optional(z.string()),
    password: z.optional(z.string()),
  }),
)

/**
 * @description successful operation
 */
export const loginUserStatus200Schema = z.string()

/**
 * @description Invalid username/password supplied
 */
export const loginUserStatus400Schema = z.any()

export const loginUserResponseDataSchema = z.lazy(() => loginUserStatus200Schema)
