/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod/mini";

/**
 * @description successful operation
 */
export const logoutUserErrorSchema = z.any();

export const logoutUserQueryResponseSchema = z.any();
