/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { categorySchema } from "./categorySchema.ts";
import { tagSchema } from "./tagSchema.ts";
import { z } from "zod/mini";

export const petSchema = z.object({
    "id": z.optional(z.int()),
get "parent"(){
                return z.array(petSchema).optional()
              },
"internalId": z.optional(z.string().check(z.regex(/^[0-9]{1,19}$/))),
"name": z.string(),
get "category"(){
                return categorySchema.optional()
              },
"photoUrls": z.array(z.string()),
get "tags"(){
                return z.array(tagSchema).optional()
              },
"status": z.optional(z.enum(["available", "pending", "sold"]).describe("pet status in the store"))
    })

export type PetSchema = z.infer<typeof petSchema>