/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'
import { phoneNumberSchema } from './phoneNumberSchema.ts'

export const phoneWithMaxLengthExplicitSchema = z.lazy(() => phoneNumberSchema).and(z.string().check(z.maxLength(15)))
