/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod/mini";

export const tagSchema = z.object({
  id: z.optional(z.int()),
  name: z.optional(z.string()),
});
