/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod/mini";
import { petSchema } from "./petSchema.ts";

/**
 * @description Successful operation
 */
export const updatePet200Schema = z.lazy(() => petSchema);

/**
 * @description Invalid ID supplied
 */
export const updatePet400Schema = z.any();

/**
 * @description Pet not found
 */
export const updatePet404Schema = z.any();

/**
 * @description Validation exception
 */
export const updatePet405Schema = z.any();

/**
 * @description Update an existent pet in the store
 */
export const updatePetMutationRequestSchema = z.lazy(() => petSchema);

export const updatePetMutationResponseSchema = z.lazy(() => updatePet200Schema);
