/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/mini'
import { petSchema } from './petSchema.ts'

/**
 * @description Successful operation
 */
export const updatePetStatus200Schema = z.lazy(() => petSchema)

/**
 * @description Invalid ID supplied
 */
export const updatePetStatus400Schema = z.any()

/**
 * @description Pet not found
 */
export const updatePetStatus404Schema = z.any()

/**
 * @description Validation exception
 */
export const updatePetStatus405Schema = z.any()

/**
 * @description Update an existent pet in the store
 */
export const updatePetRequestDataSchema = z.lazy(() => petSchema)

export const updatePetResponseDataSchema = z.lazy(() => updatePetStatus200Schema)
