/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cat } from './Cat.ts'
import type { Category } from './Category.ts'
import type { Dog } from './Dog.ts'
import type { Tag } from './Tag.ts'

export type Pet = (
  | (Dog & {
      /**
       * @type string
       */
      readonly type: 'dog'
    })
  | (Cat & {
      /**
       * @type string
       */
      readonly type: 'cat'
    })
) & {
  /**
   * @example 10
   * @type integer | undefined
   */
  id?: number
  /**
   * @type string
   */
  readonly type: 'dog' | 'cat'
  /**
   * @example doggie
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category?: Category
  /**
   * @type array
   */
  photoUrls: string[]
  /**
   * @type array | undefined
   */
  readonly tags?: Tag[]
  /**
   * @description pet status in the store
   * @type string | undefined
   */
  status?: 'available' | 'pending' | 'sold'
}
