/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker'

/**
 * @description Null response
 */
export function createPets201() {
  return undefined
}

/**
 * @description unexpected error
 */
export function createPetsError() {
  return error()
}

export function createPetsMutationRequest(data?: Partial<CreatePetsMutationRequest>) {
  return {
    ...{ name: faker.string.alpha(), tag: faker.string.alpha() },
    ...(data || {}),
  } as CreatePetsMutationRequest
}

export function createPetsMutationResponse(data?: Partial<CreatePetsMutationResponse>) {
  return data || (faker.helpers.arrayElement<any>([createPets201()]) as CreatePetsMutationResponse)
}
