/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export function deletePetsPetidMutationResponse(data?: Partial<DeletePetsPetidMutationResponse>): DeletePetsPetidMutationResponse {
  return undefined
}
