/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker'

export function enumNamesType() {
  return faker.helpers.arrayElement<EnumNamesType>([0, 1])
}
