/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker'

export function enumVarNamesType() {
  return faker.helpers.arrayElement<EnumVarNamesType>([0, 1])
}
