/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker'

export function float(data?: number) {
  return data ?? (faker.number.float() as number)
}
