/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker'

export function listPetsQueryParams(data?: Partial<ListPetsQueryParams>) {
  return {
    ...{ limit: faker.string.alpha() },
    ...(data || {}),
  } as ListPetsQueryParams
}

/**
 * @description A paged array of pets
 */
export function listPets200(data?: Partial<ListPets200>) {
  return {
    ...{ ...pagination(), ...pets() },
    ...(data || {}),
  } as ListPets200
}

/**
 * @description unexpected error
 */
export function listPetsError() {
  return error()
}

export function listPetsQueryResponse(data?: Partial<ListPetsQueryResponse>) {
  return data || (faker.helpers.arrayElement<any>([listPets200()]) as ListPetsQueryResponse)
}
