/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker'

/**
 * @description Pet adoption error codes
 */
export function petAdoptionError() {
  return faker.helpers.arrayElement<PetAdoptionError>(['pet_not_found', 'already_adopted', 'age_restriction'])
}
