/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { faker } from '@faker-js/faker'

export function showPetByIdPathParams(data?: Partial<ShowPetByIdPathParams>): ShowPetByIdPathParams {
  return {
    ...{ petId: faker.string.alpha(), testId: faker.string.alpha() },
    ...(data || {}),
  }
}

/**
 * @description Expected response to a valid request
 */
export function showPetById200(data?: Partial<ShowPetById200>): ShowPetById200 {
  return pet(data)
}

/**
 * @description unexpected error
 */
export function showPetByIdError(data?: Partial<ShowPetByIdError>): ShowPetByIdError {
  return error(data)
}

export function showPetByIdQueryResponse(data?: Partial<ShowPetByIdQueryResponse>): ShowPetByIdQueryResponse {
  return data || faker.helpers.arrayElement<any>([showPetById200()])
}
