/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Config } from "./Config.ts";

export type GetConfigIdV20250PathConfigId = string;

/**
 * @description Configuration response
*/
export type GetConfigIdV20250Status200 = Config;

export type GetConfigIdV20250RequestConfig = {
    data?: never;
    pathParams: {
        config_id: GetConfigIdV20250PathConfigId;
    };
    queryParams?: never;
    headerParams?: never;
    url: `/config/${string}`;
};

export type GetConfigIdV20250Responses = {
    "200": GetConfigIdV20250Status200;
};

/**
 * @description Union of all possible responses
*/
export type GetConfigIdV20250Response = GetConfigIdV20250Status200;