/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { Client, RequestConfig, ResponseErrorConfig } from './test/.kubb/fetch'
import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import { fetch } from './test/.kubb/fetch'
import { mutationOptions, useMutation } from '@tanstack/react-query'

export const deletePetMutationKey = (petId: DeletePetPathParams['petId']) => [{ url: '/pet/:pet_id', params: { pet_id: pet_id } }] as const

export type DeletePetMutationKey = ReturnType<typeof deletePetMutationKey>

/**
 * @description delete a pet
 * @summary Deletes a pet
 * {@link /pet/:pet_id}
 */
export async function deletePet(
  petId: DeletePetPathParams['petId'],
  headers?: DeletePetHeaderParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<DeletePetMutationResponse, ResponseErrorConfig<DeletePet400>, unknown>({
    method: 'DELETE',
    url: `/pet/${pet_id}`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return deletePetMutationResponse.parse(res.data)
}

export function deletePetMutationOptions<TContext = unknown>(petId: DeletePetPathParams['petId'], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deletePetMutationKey(petId)
  return mutationOptions<
    DeletePetMutationResponse,
    ResponseErrorConfig<DeletePet400>,
    { petId: DeletePetPathParams['petId']; headers?: DeletePetHeaderParams },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ petId, headers }) => {
      return deletePet(petId, headers, config)
    },
  })
}

/**
 * @description delete a pet
 * @summary Deletes a pet
 * {@link /pet/:pet_id}
 */
export function useDeletePet<TContext>(
  petId: DeletePetPathParams['petId'],
  options: {
    mutation?: UseMutationOptions<
      DeletePetMutationResponse,
      ResponseErrorConfig<DeletePet400>,
      { petId: DeletePetPathParams['petId']; headers?: DeletePetHeaderParams },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deletePetMutationKey(petId)

  const baseOptions = deletePetMutationOptions(petId, config) as UseMutationOptions<
    DeletePetMutationResponse,
    ResponseErrorConfig<DeletePet400>,
    { petId: DeletePetPathParams['petId']; headers?: DeletePetHeaderParams },
    TContext
  >

  return useMutation<
    DeletePetMutationResponse,
    ResponseErrorConfig<DeletePet400>,
    { petId: DeletePetPathParams['petId']; headers?: DeletePetHeaderParams },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeletePetMutationResponse,
    ResponseErrorConfig<DeletePet400>,
    { petId: DeletePetPathParams['petId']; headers?: DeletePetHeaderParams },
    TContext
  >
}
