/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { RequestConfig, ResponseErrorConfig } from './test/.kubb/fetch'
import type { InfiniteData, QueryKey, QueryClient, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult } from '@tanstack/react-query'
import { fetch } from './test/.kubb/fetch'
import { infiniteQueryOptions, useSuspenseInfiniteQuery } from '@tanstack/react-query'

export const findPetsByStatusSuspenseInfiniteQueryKey = (params: FindPetsByStatusQueryParams = {}) =>
  [{ url: '/pet/findByStatus' }, ...(params ? [params] : [])] as const

export type FindPetsByStatusSuspenseInfiniteQueryKey = ReturnType<typeof findPetsByStatusSuspenseInfiniteQueryKey>

/**
 * @description Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 * {@link /pet/findByStatus}
 */
export async function findPetsByStatusSuspenseInfinite(
  { params }: { params?: FindPetsByStatusQueryParams } = {},
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindPetsByStatusQueryResponse, ResponseErrorConfig<FindPetsByStatus400>, unknown>({
    method: 'GET',
    url: `/pet/findByStatus`,
    params,
    ...requestConfig,
  })
  return findPetsByStatusQueryResponse.parse(res.data)
}

export function findPetsByStatusSuspenseInfiniteQueryOptions(
  { params }: { params?: FindPetsByStatusQueryParams } = {},
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByStatusSuspenseInfiniteQueryKey(params)
  return infiniteQueryOptions<
    FindPetsByStatusQueryResponse,
    ResponseErrorConfig<FindPetsByStatus400>,
    InfiniteData<FindPetsByStatusQueryResponse>,
    typeof queryKey,
    NonNullable<FindPetsByStatusQueryParams['status']>
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      params = {
        ...(params ?? {}),
        ['status']: pageParam as unknown as FindPetsByStatusQueryParams['status'],
      } as FindPetsByStatusQueryParams
      return findPetsByStatusSuspenseInfinite({ params }, config)
    },
    initialPageParam: 'available',
    getNextPageParam: (lastPage, _allPages, lastPageParam) => (Array.isArray(lastPage) && lastPage.length === 0 ? undefined : lastPageParam + 1),
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) => (firstPageParam <= 1 ? undefined : firstPageParam - 1),
  })
}

/**
 * @description Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 * {@link /pet/findByStatus}
 */
export function useFindPetsByStatusSuspenseInfinite<
  TQueryFnData = FindPetsByStatusQueryResponse,
  TError = ResponseErrorConfig<FindPetsByStatus400>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = FindPetsByStatusSuspenseInfiniteQueryKey,
  TPageParam = NonNullable<FindPetsByStatusQueryParams['status']>,
>(
  { params }: { params?: FindPetsByStatusQueryParams } = {},
  options: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? findPetsByStatusSuspenseInfiniteQueryKey(params)

  const query = useSuspenseInfiniteQuery(
    {
      ...findPetsByStatusSuspenseInfiniteQueryOptions({ params }, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
