/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getPetById = (petId: GetPetByIdPathParams['pet_id']) => [{ url: '/pet/:pet_id', params: { petId: petId } }] as const

export type GetPetById = ReturnType<typeof getPetById>
