/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { Client, RequestConfig, ResponseErrorConfig } from './test/.kubb/fetch'
import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import { fetch } from './test/.kubb/fetch'
import { mutationOptions, useMutation } from '@tanstack/react-query'

export const createOrderMutationKey = () => [{ url: '/orders' }] as const

export type CreateOrderMutationKey = ReturnType<typeof createOrderMutationKey>

/**
 * {@link /orders}
 */
export async function createOrder(
  data: CreateOrderMutationRequest,
  headers?: CreateOrderHeaderParams,
  config: Partial<RequestConfig<CreateOrderMutationRequest>> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = createOrderMutationRequest.parse(data)

  const res = await request<CreateOrderMutationResponse, ResponseErrorConfig<Error>, CreateOrderMutationRequest>({
    method: 'POST',
    url: `/orders`,
    data: requestData,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return createOrderMutationResponse.parse(res.data)
}

export function createOrderMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreateOrderMutationRequest>> & { client?: Client } = {}) {
  const mutationKey = createOrderMutationKey()
  return mutationOptions<
    CreateOrderMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateOrderMutationRequest; headers?: CreateOrderHeaderParams },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data, headers }) => {
      return createOrder(data, headers, config)
    },
  })
}

/**
 * {@link /orders}
 */
export function useCreateOrder<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateOrderMutationResponse,
      ResponseErrorConfig<Error>,
      { data: CreateOrderMutationRequest; headers?: CreateOrderHeaderParams },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<CreateOrderMutationRequest>> & { client?: Client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? createOrderMutationKey()

  const baseOptions = createOrderMutationOptions(config) as UseMutationOptions<
    CreateOrderMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateOrderMutationRequest; headers?: CreateOrderHeaderParams },
    TContext
  >

  return useMutation<
    CreateOrderMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateOrderMutationRequest; headers?: CreateOrderHeaderParams },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateOrderMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreateOrderMutationRequest; headers?: CreateOrderHeaderParams },
    TContext
  >
}
