/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { RequestConfig, ResponseErrorConfig } from './test/.kubb/fetch'
import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import { fetch } from './test/.kubb/fetch'
import { mutationOptions, useMutation } from '@tanstack/react-query'

export const updatePetWithFormMutationKey = () => [{ url: '/pet/:pet_id' }] as const

export type UpdatePetWithFormMutationKey = ReturnType<typeof updatePetWithFormMutationKey>

/**
 * @summary Updates a pet in the store with form data
 * {@link /pet/:pet_id}
 */
export async function updatePetWithForm(
  petId: UpdatePetWithFormPathParams['petId'],
  data?: UpdatePetWithFormRequestData,
  params?: UpdatePetWithFormQueryParams,
  config: Partial<RequestConfig<UpdatePetWithFormRequestData>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = updatePetWithFormRequestData.parse(data)

  const res = await request<UpdatePetWithFormResponseData, ResponseErrorConfig<UpdatePetWithFormStatus405>, UpdatePetWithFormRequestData>({
    method: 'POST',
    url: `/pet/${pet_id}`,
    params,
    data: requestData,
    ...requestConfig,
  })
  return updatePetWithFormResponseData.parse(res.data)
}

export function updatePetWithFormMutationOptions(config: Partial<RequestConfig<UpdatePetWithFormRequestData>> & { client?: typeof fetch } = {}) {
  const mutationKey = updatePetWithFormMutationKey()
  return mutationOptions<
    UpdatePetWithFormResponseData,
    ResponseErrorConfig<UpdatePetWithFormStatus405>,
    { petId: UpdatePetWithFormPathParams['petId']; data?: UpdatePetWithFormRequestData; params?: UpdatePetWithFormQueryParams },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ petId, data, params }) => {
      return updatePetWithForm(petId, data, params, config)
    },
  })
}

/**
 * @summary Updates a pet in the store with form data
 * {@link /pet/:pet_id}
 */
export function useUpdatePetWithForm<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdatePetWithFormResponseData,
      ResponseErrorConfig<UpdatePetWithFormStatus405>,
      { petId: UpdatePetWithFormPathParams['petId']; data?: UpdatePetWithFormRequestData; params?: UpdatePetWithFormQueryParams },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<UpdatePetWithFormRequestData>> & { client?: typeof fetch }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? updatePetWithFormMutationKey()

  const baseOptions = updatePetWithFormMutationOptions(config) as UseMutationOptions<
    UpdatePetWithFormResponseData,
    ResponseErrorConfig<UpdatePetWithFormStatus405>,
    { petId: UpdatePetWithFormPathParams['petId']; data?: UpdatePetWithFormRequestData; params?: UpdatePetWithFormQueryParams },
    TContext
  >

  return useMutation<
    UpdatePetWithFormResponseData,
    ResponseErrorConfig<UpdatePetWithFormStatus405>,
    { petId: UpdatePetWithFormPathParams['petId']; data?: UpdatePetWithFormRequestData; params?: UpdatePetWithFormQueryParams },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdatePetWithFormResponseData,
    ResponseErrorConfig<UpdatePetWithFormStatus405>,
    { petId: UpdatePetWithFormPathParams['petId']; data?: UpdatePetWithFormRequestData; params?: UpdatePetWithFormQueryParams },
    TContext
  >
}
