/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { RequestConfig, ResponseErrorConfig } from './test/.kubb/fetch'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { FindInfiniteByTags } from './findInfiniteByTags'
import { fetch } from './test/.kubb/fetch'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'
import { findInfiniteByTags } from './findInfiniteByTags'

export const findPetsByTags = (params?: FindInfiniteByTags) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type FindInfiniteByTagsInfiniteQueryKey = ReturnType<typeof findPetsByTags>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function findInfiniteByTagsInfinite(
  headers: FindInfiniteByTags,
  params?: FindInfiniteByTags,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindInfiniteByTags, ResponseErrorConfig<FindInfiniteByTags>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return findInfiniteByTags.parse(res.data)
}

export function findInfiniteByTagsInfiniteQueryOptions(
  headers: FindInfiniteByTags,
  params?: FindInfiniteByTags,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByTags(params)
  return infiniteQueryOptions<
    FindInfiniteByTags,
    ResponseErrorConfig<FindInfiniteByTags>,
    InfiniteData<FindInfiniteByTags>,
    typeof queryKey,
    NonNullable<FindInfiniteByTags['pageSize']>
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      params = {
        ...(params ?? {}),
        ['pageSize']: pageParam as unknown as FindInfiniteByTags['pageSize'],
      } as FindInfiniteByTags
      return findInfiniteByTagsInfinite(headers, params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) => (Array.isArray(lastPage) && lastPage.length === 0 ? undefined : lastPageParam + 1),
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) => (firstPageParam <= 1 ? undefined : firstPageParam - 1),
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function useFindInfiniteByTagsInfinite<
  TQueryFnData = FindInfiniteByTags,
  TError = ResponseErrorConfig<FindInfiniteByTags>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = FindInfiniteByTagsInfiniteQueryKey,
  TPageParam = NonNullable<FindInfiniteByTags['pageSize']>,
>(
  headers: FindInfiniteByTags,
  params?: FindInfiniteByTags,
  options: {
    query?: Partial<InfiniteQueryObserverOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? findPetsByTags(params)

  const query = useInfiniteQuery(
    {
      ...findInfiniteByTagsInfiniteQueryOptions(headers, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as InfiniteQueryObserverOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
