/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { RequestConfig, ResponseErrorConfig } from './test/.kubb/fetch'
import type { InfiniteData, QueryKey, QueryClient, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult } from '@tanstack/react-query'
import type { FindSuspenseInfiniteByTags } from './findSuspenseInfiniteByTags'
import { fetch } from './test/.kubb/fetch'
import { infiniteQueryOptions, useSuspenseInfiniteQuery } from '@tanstack/react-query'
import { findSuspenseInfiniteByTags } from './findSuspenseInfiniteByTags'

export const findPetsByTags = (params?: FindSuspenseInfiniteByTags) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type FindSuspenseInfiniteByTagsSuspenseInfiniteQueryKey = ReturnType<typeof findPetsByTags>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function findSuspenseInfiniteByTagsSuspenseInfinite(
  headers: FindSuspenseInfiniteByTags,
  params?: FindSuspenseInfiniteByTags,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindSuspenseInfiniteByTags, ResponseErrorConfig<FindSuspenseInfiniteByTags>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return findSuspenseInfiniteByTags.parse(res.data)
}

export function findSuspenseInfiniteByTagsSuspenseInfiniteQueryOptions(
  headers: FindSuspenseInfiniteByTags,
  params?: FindSuspenseInfiniteByTags,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByTags(params)
  return infiniteQueryOptions<
    FindSuspenseInfiniteByTags,
    ResponseErrorConfig<FindSuspenseInfiniteByTags>,
    InfiniteData<FindSuspenseInfiniteByTags>,
    typeof queryKey,
    NonNullable<FindSuspenseInfiniteByTags['pageSize']>
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      params = {
        ...(params ?? {}),
        ['pageSize']: pageParam as unknown as FindSuspenseInfiniteByTags['pageSize'],
      } as FindSuspenseInfiniteByTags
      return findSuspenseInfiniteByTagsSuspenseInfinite(headers, params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) => (Array.isArray(lastPage) && lastPage.length === 0 ? undefined : lastPageParam + 1),
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) => (firstPageParam <= 1 ? undefined : firstPageParam - 1),
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function useFindSuspenseInfiniteByTagsSuspenseInfinite<
  TQueryFnData = FindSuspenseInfiniteByTags,
  TError = ResponseErrorConfig<FindSuspenseInfiniteByTags>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = FindSuspenseInfiniteByTagsSuspenseInfiniteQueryKey,
  TPageParam = NonNullable<FindSuspenseInfiniteByTags['pageSize']>,
>(
  headers: FindSuspenseInfiniteByTags,
  params?: FindSuspenseInfiniteByTags,
  options: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? findPetsByTags(params)

  const query = useSuspenseInfiniteQuery(
    {
      ...findSuspenseInfiniteByTagsSuspenseInfiniteQueryOptions(headers, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
