/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type integer | undefined
 */
export type FindArtifactsQueryPage = number | undefined

/**
 * @type integer | undefined
 */
export type FindArtifactsQueryLimit = number | undefined

/**
 * @type string | undefined
 */
export type FindArtifactsQuerySort = string | undefined

/**
 * @type object
 */
export type FindArtifactsStatus200 = object

/**
 * @type object
 */
export type FindArtifactsRequestConfig = {
  data?: never
  pathParams?: never
  /**
   * @type object | undefined
   */
  queryParams?: {
    page?: FindArtifactsQueryPage
    limit?: FindArtifactsQueryLimit
    sort?: FindArtifactsQuerySort
  }
  headerParams?: never
  /**
   * @type string
   */
  url: '/artifacts'
}

/**
 * @type object
 */
export type FindArtifactsResponses = {
  '200': FindArtifactsStatus200
}

/**
 * @description Union of all possible responses
 */
export type FindArtifactsResponse = FindArtifactsStatus200
