/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FindArtifactsQueryPage = number

export type FindArtifactsQueryLimit = number

export type FindArtifactsQuerySort = string

/**
 * @description Results
 */
export type FindArtifactsStatus200 = object

export type FindArtifactsRequestConfig = {
  data?: never
  pathParams?: never
  queryParams?: {
    page?: FindArtifactsQueryPage
    limit?: FindArtifactsQueryLimit
    sort?: FindArtifactsQuerySort
  }
  headerParams?: never
  url: '/artifacts'
}

export type FindArtifactsResponses = {
  '200': FindArtifactsStatus200
}

/**
 * @description Union of all possible responses
 */
export type FindArtifactsResponse = FindArtifactsStatus200
