/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteOrderPathOrderId = number

export interface DeleteOrderRequestConfig {
  data?: never
  pathParams: {
    orderId: DeleteOrderPathOrderId
  }
  queryParams?: never
  headerParams?: never
  url: `/store/order/${string}`
}
