/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

/**
 * @description Successful operation
 */
export const createUsersWithListInputStatus200Schema = z.lazy(() => User)

/**
 * @description successful operation
 */
export const createUsersWithListInputStatusDefaultSchema = z.any()

export const createUsersWithListInputDataSchema = z.array(z.lazy(() => User)).optional()