/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const deleteOrderPathOrderIdSchema = z.int().describe("ID of the order that needs to be deleted")

export const deleteOrderStatus400Schema = z.any()

export const deleteOrderStatus404Schema = z.any()