/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { userSchema } from "./userSchema.ts";

export const updateUserPathUsernameSchema = z.string().describe("name that need to be deleted")

export const updateUserStatusDefaultSchema = z.any()

export const updateUserDataSchema = userSchema.optional().describe("Update an existent user in the store")