/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const productDetailsSchema = z.object({
    "productCount": z.optional(z.number()),
"itemIds": z.array(z.string())
    })