/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { contactDetailsTypeSchema } from "./contactDetailsTypeSchema.ts";

export const typeBRequestSchema = z.object({
    "actorId": z.string(),
    "ticketId": z.string(),
    "contactDetails": contactDetailsTypeSchema
    })