/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description successful operation
*/
export type GetInventoryStatus200 = {
    [key: string]: number;
};

export type GetInventoryRequestConfig = {
    data?: never;
    pathParams?: never;
    queryParams?: never;
    headerParams?: never;
    /**
     * @type string
    */
    url: "/store/inventory";
};

export type GetInventoryResponses = {
    "200": GetInventoryStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetInventoryResponse = GetInventoryStatus200;