/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pet } from "./Pet.ts";

/**
 * @description ID of pet to return
*/
export type GetPetByIdPathPetId = number;

/**
 * @description successful operation
*/
export type GetPetByIdStatus200 = Pet;

/**
 * @description Invalid ID supplied
*/
export type GetPetByIdStatus400 = any;

/**
 * @description Pet not found
*/
export type GetPetByIdStatus404 = any;

export type GetPetByIdRequestConfig = {
    data?: never;
    /**
     * @type object
    */
    pathParams: {
        petId: GetPetByIdPathPetId;
    };
    queryParams?: never;
    headerParams?: never;
    /**
     * @type string
    */
    url: `/pet/${string}`;
};

export type GetPetByIdResponses = {
    "200": GetPetByIdStatus200;
    "400": GetPetByIdStatus400;
    "404": GetPetByIdStatus404;
};

/**
 * @description Union of all possible responses
*/
export type GetPetByIdResponse = (GetPetByIdStatus200 | GetPetByIdStatus400 | GetPetByIdStatus404);