/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import fetch from 'axios'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from 'axios'
import type { ClientGetImportPath } from './clientGetImportPath'
import type { MaybeRefOrGetter } from 'vue'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { clientGetImportPath } from './clientGetImportPath'
import { toValue } from 'vue'

export const findPetsByTags = (params?: MaybeRefOrGetter<ClientGetImportPath>) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type ClientGetImportPathQueryKey = ReturnType<typeof findPetsByTags>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function clientGetImportPath(
  headers: ClientGetImportPath,
  params?: ClientGetImportPath,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ClientGetImportPath, ResponseErrorConfig<ClientGetImportPath>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return clientGetImportPath.parse(res.data)
}

export function clientGetImportPathQueryOptions(
  headers: MaybeRefOrGetter<ClientGetImportPath>,
  params?: MaybeRefOrGetter<ClientGetImportPath>,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByTags(params)
  return queryOptions<ClientGetImportPath, ResponseErrorConfig<ClientGetImportPath>, ClientGetImportPath, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return clientGetImportPath(toValue(headers), toValue(params), toValue(config))
    },
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function useClientGetImportPath<TData = ClientGetImportPath, TQueryData = ClientGetImportPath, TQueryKey extends QueryKey = ClientGetImportPathQueryKey>(
  headers: MaybeRefOrGetter<ClientGetImportPath>,
  params?: MaybeRefOrGetter<ClientGetImportPath>,
  options: {
    query?: Partial<UseQueryOptions<ClientGetImportPath, ResponseErrorConfig<ClientGetImportPath>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = (queryOptions && 'queryKey' in queryOptions ? toValue(queryOptions.queryKey) : undefined) ?? findPetsByTags(params)

  const query = useQuery(
    {
      ...clientGetImportPathQueryOptions(headers, params, config),
      ...queryOptions,
      queryKey,
    } as unknown as UseQueryOptions<ClientGetImportPath, ResponseErrorConfig<ClientGetImportPath>, TData, ClientGetImportPath, TQueryKey>,
    toValue(queryClient),
  ) as UseQueryReturnType<TData, ResponseErrorConfig<ClientGetImportPath>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
