/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const paramsChannelEnum = {
    public: "public",
    collaborators: "collaborators"
} as const;

export type ParamsChannelEnumKey = (typeof paramsChannelEnum)[keyof typeof paramsChannelEnum];

export type ParamsChannelEnum = ParamsChannelEnumKey

export type NotificationTypeA = {
    /**
     * @type string
    */
    type: string;
    /**
     * @type object
    */
    params: {
        /**
         * @type string
        */
        channel: ParamsChannelEnumKey;
        /**
         * @type string
        */
        messageA: string;
    };
};