/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description successful operation
 */
export type LogoutUserStatusDefault = any

export interface LogoutUserRequestConfig {
  data?: never
  pathParams?: never
  queryParams?: never
  headerParams?: never
  url: '/user/logout'
}

export interface LogoutUserResponses {
  default: LogoutUserStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type LogoutUserResponse = LogoutUserStatusDefault
