/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import fetch from 'axios'
import type { UseQueryOptions, UseQueryReturn } from '@pinia/colada'
import type { RequestConfig, ResponseErrorConfig } from 'axios'
import type { MaybeRefOrGetter } from 'vue'
import { defineQuery, useQuery } from '@pinia/colada'
import { toValue } from 'vue'

export const findPetsByTagsQueryKey = (params?: MaybeRefOrGetter<FindPetsByTagsQueryParams>) =>
  [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type FindPetsByTagsQueryKey = ReturnType<typeof findPetsByTagsQueryKey>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function findPetsByTags(
  headers: FindPetsByTagsHeaderParams,
  params?: FindPetsByTagsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindPetsByTagsQueryResponse, ResponseErrorConfig<FindPetsByTags400>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })
  return findPetsByTagsQueryResponse.parse(res.data)
}

export function findPetsByTagsQueryOptions(
  headers: MaybeRefOrGetter<FindPetsByTagsQueryParams>,
  params?: MaybeRefOrGetter<FindPetsByTagsQueryParams>,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = findPetsByTagsQueryKey(params)
  return defineQuery<FindPetsByTagsQueryResponse, ResponseErrorConfig<FindPetsByTags400>, FindPetsByTagsQueryResponse, typeof queryKey>({
    key: queryKey,
    query: async ({ signal }) => {
      config.signal = signal
      return findPetsByTags(toValue(headers), toValue(params), toValue(config))
    },
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function useFindPetsByTags<TData = FindPetsByTagsQueryResponse>(
  headers: MaybeRefOrGetter<FindPetsByTagsHeaderParams>,
  params?: MaybeRefOrGetter<FindPetsByTagsQueryParams>,
  options: {
    query?: Partial<UseQueryOptions<FindPetsByTagsQueryResponse, ResponseErrorConfig<FindPetsByTags400>>>
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryOptions = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.key ?? findPetsByTagsQueryKey(params)

  const query = useQuery({
    ...findPetsByTagsQueryOptions(headers, params, config),
    ...queryOptions,
    key: queryKey,
  }) as UseQueryReturn<FindPetsByTagsQueryResponse, ResponseErrorConfig<FindPetsByTags400>>

  return query
}
