/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Borough } from '../Borough.ts'
import type { Error } from '../Error.ts'

/**
 * @description An object containing all boroughs.
 */
export type FindBoroughs200 = {
  /**
   * @type array
   */
  boroughs: Borough[]
}

/**
 * @description Invalid client request
 */
export type FindBoroughs400 = Error

/**
 * @description Server side error
 */
export type FindBoroughs500 = Error

export type FindBoroughsQuery = {
  Response: FindBoroughs200
  Errors: FindBoroughs400 | FindBoroughs500
}

export type FindBoroughsQueryResponse = FindBoroughs200
