/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ElectricCar } from "./ElectricCar.ts";
import type { SUV } from "./SUV.ts";
import type { Sedan } from "./Sedan.ts";

export type VehicleChoice = ((Sedan & {
    type: "Sedan";
}) | (SUV & {
    type: "SUV";
}) | (ElectricCar & {
    type: "ElectricCar";
}));