openapi: 3.1.0
info:
  title: exclusive number test cases
  version: 1.0.0

components:
  schemas:
    ExclusiveNumbers:
      type: object
      properties:
        exclusiveMin:
          type: number
          exclusiveMinimum: 0
        exclusiveMax:
          type: number
          exclusiveMaximum: 10
        exclusiveRange: 
          type: number
          exclusiveMaximum: 9.99
          exclusiveMinimum: 0.01
        strictMinExclusiveMaxRange: 
          type: number
          exclusiveMaximum: 1000
          minimum: 0
        strictMaxExclusiveMinRange: 
          type: number
          maximum: 1000
          exclusiveMinimum: 0
        exclusiveIntRange:
          type: integer
          exclusiveMaximum: 9
          exclusiveMinimum: 0
      required:
        - exclusiveRange