definitions:
  Nullable:
    type: ["object", "null"]
    properties:
      foo:
        type: ["string", "null"]
openapi: 3.1.0
info:
  title: test
  version: "1.0.0"
paths:
  /names:
    get:
      consumes:
        - application/json
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Nullable"
components:
  schemas:
    Nullable:
      type: ["object", "null"]
      properties:
        foo:
          type: ["string", "null"]
