/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "./User.ts";

/**
 * @description Successful operation
*/
export type CreateUsersWithListInputStatus200 = User;

/**
 * @description successful operation
*/
export type CreateUsersWithListInputStatusError = any;

export type CreateUsersWithListInputRequestData = User[];

export type CreateUsersWithListInputResponseData = CreateUsersWithListInputStatus200;

export type CreateUsersWithListInputRequest = {
    data?: CreateUsersWithListInputRequest;
    pathParams?: never;
    queryParams?: never;
    headerParams?: never;
    url: "/user/createWithList";
};

export type CreateUsersWithListInputResponses = {
    "200": CreateUsersWithListInputResponse;
};


export type CreateUsersWithListInputResponseData = CreateUsersWithListInputResponses[keyof CreateUsersWithListInputResponses];