/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeletePetPathParams = {
    /**
     * @description Pet id to delete
     * @type integer, int64
    */
    petId: number;
};

export type DeletePetHeaderParams = {
    /**
     * @type string | undefined
    */
    api_key?: string;
};

/**
 * @description Invalid pet value
*/
export type DeletePetStatus400 = any;

export type DeletePetResponseData = any;

export type DeletePetRequest = {
    data?: never;
    pathParams: DeletePetPathParams;
    queryParams?: never;
    headerParams?: DeletePetHeaderParams;
    url: `/pet/${string}`;
};

export type DeletePetResponseData = any;