/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description successful operation
*/
export type LogoutUserStatusError = any;

export type LogoutUserResponseData = any;

export type LogoutUserRequest = {
    data?: never;
    pathParams?: never;
    queryParams?: never;
    headerParams?: never;
    url: "/user/logout";
};

export type LogoutUserResponseData = any;