/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Order } from "./Order.ts";

/**
 * @description successful operation
*/
export type PlaceOrderStatus200 = Order;

/**
 * @description Invalid input
*/
export type PlaceOrderStatus405 = any;

export type PlaceOrderRequestData = Order;

export type PlaceOrderResponseData = PlaceOrderStatus200;

export type PlaceOrderRequest = {
    data?: PlaceOrderRequest;
    pathParams?: never;
    queryParams?: never;
    headerParams?: never;
    url: "/store/order";
};

export type PlaceOrderResponses = {
    "200": PlaceOrderResponse;
};


export type PlaceOrderResponseData = PlaceOrderResponses[keyof PlaceOrderResponses];