/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pet } from "./Pet.ts";

/**
 * @description Successful operation
*/
export type UpdatePetStatus200 = Pet;

/**
 * @description Invalid ID supplied
*/
export type UpdatePetStatus400 = any;

/**
 * @description Pet not found
*/
export type UpdatePetStatus404 = any;

/**
 * @description Validation exception
*/
export type UpdatePetStatus405 = any;

/**
 * @description Update an existent pet in the store
*/
export type UpdatePetRequestData = Pet;

export type UpdatePetResponseData = UpdatePetStatus200;

export type UpdatePetRequest = {
    data?: UpdatePetRequest;
    pathParams?: never;
    queryParams?: never;
    headerParams?: never;
    url: "/pet";
};

export type UpdatePetResponses = {
    "200": UpdatePetResponse;
};


export type UpdatePetResponseData = UpdatePetResponses[keyof UpdatePetResponses];