/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeletePetPathPetId = string

/**
 * @description No content
 */
export type DeletePetStatus204 = void

export type DeletePetRequestConfig = {
  data?: never
  /**
   * @type object
   */
  pathParams: {
    petId: DeletePetPathPetId
  }
  queryParams?: never
  headerParams?: never
  /**
   * @type string
   */
  url: `/pets/${string}`
}

export type DeletePetResponses = {
  '204': DeletePetStatus204
}

/**
 * @description Union of all possible responses
 */
export type DeletePetResponse = DeletePetStatus204
