# Based on Bun's template

name: Bug Report
description: Report an issue that should be fixed
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. It helps make `Kubb` better.
  - type: input
    attributes:
      label: What version of `kubb` is running?
      description: Copy the output of `kubb -v`
  - type: dropdown
    attributes:
      label: What kind of platform do you use?
      options:
        - MacOS
        - Windows
        - Linux
      description: MacOS, Windows, Linux.
  - type: textarea
    attributes:
      label: Your `kubb.config.ts` config file?
      description: Copy-paste your Kubb config
      render: typescript
  - type: textarea
    attributes:
      label: Swagger/OpenAPI file?
      description: If possible, please provide your Swagger/OpenAPI file.
      render: bash
  - type: textarea
    attributes:
      label: What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)
      description: Copy the output of your `package.json`
      render: JSON
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: |
        Explain the bug and provide a code snippet that can reproduce it.
         Please add a link to a minimal reproduction.
        Note:
        - Your bug may get fixed much faster if we can run your code, and it doesn't have dependencies other than React/Solid/Vue/Svelte.
        - To create a shareable code example, use CodeSandbox (https://codesandbox.io/s/new) or Stackblitz (https://stackblitz.com/).
        - For TypeScript-related issues only, a TypeScript Playground link might be sufficient: https://www.typescriptlang.org/play
        - Please read these tips for providing a minimal example: https://stackoverflow.com/help/mcve
    validations:
      required: true
  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: |
        Following the repro steps above, how easily are you able to reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
  - type: textarea
    attributes:
      label: What is the expected behaviour?
      description: If possible, please provide text instead of a screenshot.
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
