# Based on Bun's template

name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an idea. It helps make `Kubb` better.
  - type: textarea
    attributes:
      label: What is the problem this feature would solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: External documents/projects?
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
  - type: textarea
    attributes:
      label: What alternatives have you considered?
