/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { apiResponseSchema } from "../apiResponseSchema.ts";

export const uploadFilePathPetIdSchema = z.int().describe("ID of pet to update")

export const uploadFileQueryAdditionalMetadataSchema = z.string().optional().describe("Additional Metadata")

/**
 * @description successful operation
 */
export const uploadFileStatus200Schema = apiResponseSchema

export const uploadFileDataSchema = z.instanceof(File).optional()