/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { ListPetsQueryLimit, ListPetsResponse } from './ListPets'

export function listPets(params?: { limit?: ListPetsQueryLimit }, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<ListPetsResponse> {
  return cy
    .request<ListPetsResponse>({
      method: 'get',
      url: `${123456}/pets`,
      qs: params,
      ...options,
    })
    .then((res) => res.body)
}
