components:
  schemas:
    CreateUser:
      properties:
        email:
          type: string
    CreateUserResult:
      properties:
        success:
          type: boolean
      required:
        - success
      type: object
info:
  license:
    name: MIT
  title: Kubb Sample
  version: 1.0.0
openapi: '3.0.0'
paths:
  /pets:
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResult'
          description: OK
