openapi: '3.0.3'
info:
  title: Fragment Ref API
  version: 1.0.0
paths: {}
components:
  schemas:
    Household:
      type: object
      properties:
        cat:
          $ref: './external/animals.yaml#/components/schemas/Cat'
