/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdatePetWithFormPathPetId = number

export type UpdatePetWithFormQueryName = string

export type UpdatePetWithFormQueryStatus = string

/**
 * @description Success
 */
export type UpdatePetWithFormStatus200 = void

/**
 * @description Invalid input
 */
export type UpdatePetWithFormStatus405 = object

export type UpdatePetWithFormRequestConfig = {
  data?: never
  /**
   * @type object
   */
  pathParams: {
    petId: UpdatePetWithFormPathPetId
  }
  /**
   * @type object | undefined
   */
  queryParams?: {
    name?: UpdatePetWithFormQueryName
    status?: UpdatePetWithFormQueryStatus
  }
  headerParams?: never
  /**
   * @type string
   */
  url: `/pet/${string}`
}

export type UpdatePetWithFormResponses = {
  '200': UpdatePetWithFormStatus200
  '405': UpdatePetWithFormStatus405
}

/**
 * @description Union of all possible responses
 */
export type UpdatePetWithFormResponse = UpdatePetWithFormStatus200 | UpdatePetWithFormStatus405
