/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const deletePetHeaderApiKeySchema = z.coerce.string().optional()

export const deletePetPathPetIdSchema = z.coerce.number().int().describe("Pet id to delete")

/**
 * @description Invalid pet value
 */
export const deletePetStatus400Schema = z.any()