/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const getPetByIdPathPetIdSchema = z.coerce.number().int().describe("ID of pet to return")

/**
 * @description successful operation
 */
export const getPetByIdStatus200Schema = z.lazy(() => Pet)

/**
 * @description Invalid ID supplied
 */
export const getPetByIdStatus400Schema = z.any()

/**
 * @description Pet not found
 */
export const getPetByIdStatus404Schema = z.any()