/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const loginUserQueryUsernameSchema = z.coerce.string().optional().describe("The user name for login")

export const loginUserQueryPasswordSchema = z.coerce.string().optional().describe("The password for login in clear text")

/**
 * @description successful operation
 */
export const loginUserStatus200Schema = z.coerce.string()

/**
 * @description Invalid username/password supplied
 */
export const loginUserStatus400Schema = z.any()