/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { categorySchema } from "./categorySchema.ts";
import { tagSchema } from "./tagSchema.ts";

export const petSchema = z.object({
    "id": z.coerce.number().int().optional(),
    "name": z.coerce.string(),
    "log": z.coerce.string().min(2).max(42).regex(/^[A-Za-z0-9()\[\]'"][-A-Za-z0-9_. \/()\[\]]{0,40}[A-Za-z0-9()\[\]'"]$/).optional(),
    "category": categorySchema.optional(),
    "photoUrls": z.array(z.coerce.string()),
    "tags": z.array(tagSchema).optional(),
    "status": z.enum(["available", "pending", "sold"]).optional().describe("pet status in the store")
    })