/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const updatePetPathPetIdSchema = z.string()

export const updatePetQueryIncludeDeletedSchema = z.boolean().optional()

export const updatePetStatus200Schema = z.object({})

export const updatePetDataSchema = z.object({
  name: z.string(),
})
