/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

/**
 * @type {string}
 */
export const updatePetPathPetIdSchema = z.string()

/**
 * @type {boolean | undefined}
 */
export const updatePetQueryIncludeDeletedSchema = z.boolean().optional()

/**
 * @type {object}
 */
export const updatePetStatus200Schema = z.object({})

/**
 * @type {object}
 */
export const updatePetDataSchema = z.object({
  name: z.string(),
})
