/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

/**
 * @description Null response
 */
export const createPetsStatus201 = z.unknown()

/**
 * @description unexpected error
 */
export const createPetsStatusError = z.lazy(() => error)

export const createPetsRequestData = z.object({
  name: z.string(),
  tag: z.string(),
})

export const createPetsResponseData = z.lazy(() => createPetsStatus201)
