/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from '@hono/zod-openapi'

/**
 * @description Null response
 */
export const createPetsStatus201 = z.unknown()

/**
 * @description unexpected error
 */
export const createPetsStatusError = z
  .lazy(() => error)
  .openapi({
    examples: [
      { sample: { summary: 'A sample error', value: { code: 1, message: 'A sample error message' } } },
      { other_example: { summary: 'Another sample error', value: { code: 2, message: 'A totally specific message' } } },
    ],
  })

export const createPetsRequestData = z.object({
  name: z.string().openapi({ example: 'Baxter' }),
  tag: z.string(),
})

export const createPetsResponseData = z.lazy(() => createPetsStatus201)
