/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from '@hono/zod-openapi'

export const deletePet = z.object({
  petId: z.number().int().describe('Pet id to delete'),
})
