/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

export const advanced = z.union([
  enumerationValueSpecificationDto.and(
    z.object({
      type: z.literal('enum'),
    }),
  ),
  rangeValueSpecificationDto.and(
    z.object({
      type: z.literal('range'),
    }),
  ),
  regexValueSpecificationDto.and(
    z.object({
      type: z.literal('regex'),
    }),
  ),
  sliderValueSpecificationDto.and(
    z.object({
      type: z.literal('slider'),
    }),
  ),
])
