/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { z } from 'zod'
import { showPetById } from './showPetById'

export type OperationSchema = {
  readonly request: z.ZodTypeAny | undefined
  readonly parameters: {
    readonly path: z.ZodTypeAny | undefined
    readonly query: z.ZodTypeAny | undefined
    readonly header: z.ZodTypeAny | undefined
  }
  readonly responses: {
    readonly [status: number]: z.ZodTypeAny
    readonly default: z.ZodTypeAny
  }
  readonly errors: {
    readonly [status: number]: z.ZodTypeAny
  }
}

export type OperationsMap = Record<string, OperationSchema>

export const operations = {
  listPets: {
    request: undefined,
    parameters: {
      path: undefined,
      query: showPetById,
      header: undefined,
    },
    responses: {
      200: showPetById,
      default: showPetById,
    },
    errors: {},
  },
  createPets: {
    request: showPetById,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      201: showPetById,
      default: showPetById,
    },
    errors: {},
  },
  showPetById: {
    request: undefined,
    parameters: {
      path: showPetById,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: showPetById,
      default: showPetById,
    },
    errors: {},
  },
  deletePet: {
    request: undefined,
    parameters: {
      path: showPetById,
      query: undefined,
      header: showPetById,
    },
    responses: {
      400: showPetById,
      default: showPetById,
    },
    errors: {
      400: showPetById,
    },
  },
} as const

export const paths = {
  '/pets': {
    get: operations['listPets'],
    post: operations['createPets'],
  },
  '/pets/{petId}': {
    get: operations['showPetById'],
    delete: operations['deletePet'],
  },
} as const
