/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { ToZod } from './test/.kubb/ToZod'
import { z } from 'zod'

export const optionalPet = z.object({
  id: z.optional(z.number().int()),
  name: z.optional(z.string()),
  tag: z.optional(z.string()),
}) as unknown as ToZod<OptionalPet>
