/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

export const optionalPet = z.object({
  id: z.optional(z.number().int()),
  name: z.optional(z.string()),
  tag: z.optional(z.string()),
})

export type OptionalPet = z.infer<typeof optionalPet>
