/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

export const order = z.object({
  id: z.optional(z.number().int()),
  petId: z.optional(z.number().int()),
  quantity: z.optional(z.number().int()),
  shipDate: z.optional(z.date()),
  status: z.optional(z.enum(['placed', 'approved', 'delivered']).describe('Order Status')),
  complete: z.optional(z.boolean()),
})
