/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import * as z from 'zod'
import { ToZod } from './test/.kubb/ToZod'

export const pets = z.array(
  z.object({
    id: z.bigint(),
    name: z.string(),
    tag: z.optional(z.string()),
  }),
) as unknown as ToZod<Pets>
