/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

/**
 * @description Tuple of exact length 2 nested in an object
 */
export const petTupleObject = z
  .object({
    tupleProperty: z.optional(z.tuple([z.string(), z.string()])),
  })
  .describe('Tuple of exact length 2 nested in an object')
