/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

export const pet = z.object({
  id: z.int(),
  name: z.string(),
  date: z.date().optional(),
  uuid: z.uuid().optional(),
  email: z.email().optional(),
  pattern: z
    .string()
    .regex(/^[a-zA-Z0-9]{3}$/)
    .optional(),
  tag: z.string().min(5).max(100).optional(),
})
