/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

export const queryAllDefaulted = z.object({
  limit: z.number().int().min(1).max(100).default(100).describe('Maximum number of things to return'),
  skip: z.number().int().min(0).default(0).describe('Number of things to skip'),
})
