/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { z } from 'zod'

export const item = z.union([
  z
    .lazy(() => itemTypeA)
    .and(
      z.object({
        id: z.optional(z.number().int()),
        type: z.literal('typeA'),
        name: z.string(),
        createdAt: z.optional(z.date()),
      }),
    ),
  z
    .lazy(() => itemTypeB)
    .and(
      z.object({
        id: z.optional(z.number().int()),
        type: z.literal('typeB'),
        name: z.string(),
        createdAt: z.optional(z.date()),
      }),
    ),
])
