/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const createPetsHeaderParamsXEXAMPLEEnum = {
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
} as const

export type CreatePetsHeaderParamsXEXAMPLEEnumKey = (typeof createPetsHeaderParamsXEXAMPLEEnum)[keyof typeof createPetsHeaderParamsXEXAMPLEEnum]

export type CreatePetsHeaderParams = {
  /**
   * @type string
   */
  'X-EXAMPLE': CreatePetsHeaderParamsXEXAMPLEEnumKey
}

/**
 * @description Null response
 */
export type CreatePets201 = void

export type CreatePetsMutationResponse = CreatePets201

export type CreatePetsMutation = {
  Response: CreatePets201
  HeaderParams: CreatePetsHeaderParams
  Errors: any
}
