/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const deleteOrderPathOrderIdSchema = z.int().describe("ID of the order that needs to be deleted")

export type DeleteOrderPathOrderIdSchema = z.infer<typeof deleteOrderPathOrderIdSchema>

export const deleteOrderStatus400Schema = z.any()

export type DeleteOrderStatus400Schema = z.infer<typeof deleteOrderStatus400Schema>

export const deleteOrderStatus404Schema = z.any()

export type DeleteOrderStatus404Schema = z.infer<typeof deleteOrderStatus404Schema>