/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { petSchema } from "./petSchema.ts";

export const findPetsByTagsQueryTagsSchema = z.array(z.string()).optional().describe("Tags to filter by")

export type FindPetsByTagsQueryTagsSchema = z.infer<typeof findPetsByTagsQueryTagsSchema>

export const findPetsByTagsStatus200Schema = z.array(petSchema)

export type FindPetsByTagsStatus200Schema = z.infer<typeof findPetsByTagsStatus200Schema>

export const findPetsByTagsStatus400Schema = z.any()

export type FindPetsByTagsStatus400Schema = z.infer<typeof findPetsByTagsStatus400Schema>