/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const findPetsByStatusQueryStatusSchema = z.enum(["available", "pending", "sold"]).optional().default("available").describe("Status values that need to be considered for filter")

export type FindPetsByStatusQueryStatusSchema = z.infer<typeof findPetsByStatusQueryStatusSchema>

/**
 * @description successful operation
 */
export const findPetsByStatusStatus200Schema = z.array(z.lazy(() => Pet))

export type FindPetsByStatusStatus200Schema = z.infer<typeof findPetsByStatusStatus200Schema>

/**
 * @description Invalid status value
 */
export const findPetsByStatusStatus400Schema = z.any()

export type FindPetsByStatusStatus400Schema = z.infer<typeof findPetsByStatusStatus400Schema>