/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const findPetsByTagsQueryTagsSchema = z.array(z.string()).optional().describe("Tags to filter by")

export type FindPetsByTagsQueryTagsSchema = z.infer<typeof findPetsByTagsQueryTagsSchema>

/**
 * @description successful operation
 */
export const findPetsByTagsStatus200Schema = z.array(z.lazy(() => Pet))

export type FindPetsByTagsStatus200Schema = z.infer<typeof findPetsByTagsStatus200Schema>

/**
 * @description Invalid tag value
 */
export const findPetsByTagsStatus400Schema = z.any()

export type FindPetsByTagsStatus400Schema = z.infer<typeof findPetsByTagsStatus400Schema>