/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const loginUserQueryUsernameSchema = z.string().optional().describe("The user name for login")

export type LoginUserQueryUsernameSchema = z.infer<typeof loginUserQueryUsernameSchema>

export const loginUserQueryPasswordSchema = z.string().optional().describe("The password for login in clear text")

export type LoginUserQueryPasswordSchema = z.infer<typeof loginUserQueryPasswordSchema>

/**
 * @description successful operation
 */
export const loginUserStatus200Schema = z.string()

export type LoginUserStatus200Schema = z.infer<typeof loginUserStatus200Schema>

/**
 * @description Invalid username/password supplied
 */
export const loginUserStatus400Schema = z.any()

export type LoginUserStatus400Schema = z.infer<typeof loginUserStatus400Schema>