/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

/**
 * @description successful operation
 */
export const logoutUserStatusDefaultSchema = z.any()

export type LogoutUserStatusDefaultSchema = z.infer<typeof logoutUserStatusDefaultSchema>