/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

/**
 * @description successful operation
 */
export const placeOrderStatus200Schema = z.lazy(() => Order)

export type PlaceOrderStatus200Schema = z.infer<typeof placeOrderStatus200Schema>

/**
 * @description Invalid input
 */
export const placeOrderStatus405Schema = z.any()

export type PlaceOrderStatus405Schema = z.infer<typeof placeOrderStatus405Schema>

export const placeOrderDataSchema = z.lazy(() => Order).optional()

export type PlaceOrderDataSchema = z.infer<typeof placeOrderDataSchema>