/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

/**
 * @description Successful operation
 */
export const updatePetStatus200Schema = z.lazy(() => Pet)

export type UpdatePetStatus200Schema = z.infer<typeof updatePetStatus200Schema>

/**
 * @description Invalid ID supplied
 */
export const updatePetStatus400Schema = z.any()

export type UpdatePetStatus400Schema = z.infer<typeof updatePetStatus400Schema>

/**
 * @description Pet not found
 */
export const updatePetStatus404Schema = z.any()

export type UpdatePetStatus404Schema = z.infer<typeof updatePetStatus404Schema>

/**
 * @description Validation exception
 */
export const updatePetStatus405Schema = z.any()

export type UpdatePetStatus405Schema = z.infer<typeof updatePetStatus405Schema>

/**
 * @description Update an existent pet in the store
 */
export const updatePetDataSchema = z.lazy(() => Pet)

export type UpdatePetDataSchema = z.infer<typeof updatePetDataSchema>