/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { listPets, createPets, showPetById } from './findByTags'

export const handlers = [listPets(), createPets(), showPetById()] as const
