/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const enumNegativeNumberEnum = {
  '-1': -1,
  '0': 0,
  '5': 5,
} as const

export type EnumNegativeNumberEnumKey = (typeof enumNegativeNumberEnum)[keyof typeof enumNegativeNumberEnum]

export type enumNegativeNumber = EnumNegativeNumberEnumKey
