/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Vehicle } from "./Vehicle.ts";

export const typeEnum2 = {
    SUV: "SUV"
} as const;

export type TypeEnum2Key = (typeof typeEnum2)[keyof typeof typeEnum2];

export type SUV = (Vehicle & {
    type?: TypeEnum2Key;
    /**
     * @description Can handle offroad terrain
    */
    offroadCapability?: boolean;
});