/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ElectricCar } from "./ElectricCar.ts";
import type { Sedan } from "./Sedan.ts";
import type { SUV } from "./SUV.ts";

export type VehicleChoice = (Sedan | SUV | ElectricCar);