/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { UpdatePetPathPetId, UpdatePetData, UpdatePetResponse } from './UpdatePet'

export function updatePet(
  petId: UpdatePetPathPetId,
  data?: UpdatePetData,
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<UpdatePetResponse> {
  return cy
    .request<UpdatePetResponse>({
      method: 'PUT',
      url: `/pets/${petId}`,
      body: data,
      ...options,
    })
    .then((res) => res.body)
}
