/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const operations = {
  findPetsByTags: {
    path: '/pet/findByTags',
    method: 'get',
  },
  updatePetWithForm: {
    path: '/pet/:petId',
    method: 'post',
  },
  deletePet: {
    path: '/pet/:petId',
    method: 'delete',
  },
}
