/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig } from './.kubb/fetch'
import { petService } from './petService/petService'

export class PetStoreClient {
  readonly petService: petService

  constructor(config: Partial<RequestConfig> & { client?: Client } = {}) {
    this.petService = new petService(config)
  }
}
