/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { DeletePetPathParams, DeletePetHeaderParams, DeletePetMutationResponse } from './models/DeletePet'

export function deletePet(
  petId: DeletePetPathParams['petId'],
  headers?: DeletePetHeaderParams,
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<DeletePetMutationResponse> {
  return cy
    .request<DeletePetMutationResponse>({
      method: 'delete',
      url: `/pets/${petId}`,
      headers,
      ...options,
    })
    .then((res) => res.body)
}
