/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const contactDetailsTypeSchema = z.object({
    "fullName": z.string(),
"emailAddress": z.string()
    })