/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const placeOrderPatchPathOrderIdSchema = z.int()

/**
 * @description Successful operation
 */
export const placeOrderPatchStatus200Schema = z.object({})

/**
 * @description Invalid input
 */
export const placeOrderPatchStatus405Schema = z.object({})

export const placeOrderPatchDataSchema = z.object({}).describe('Order payload')
