/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const notificationTypeAParamsChannelEnum = {
    public: "public",
    collaborators: "collaborators"
} as const;

export type NotificationTypeAParamsChannelEnumKey = (typeof notificationTypeAParamsChannelEnum)[keyof typeof notificationTypeAParamsChannelEnum];

/**
 * @type object
*/
export type NotificationTypeA = {
    /**
     * @type string
    */
    type: string;
    /**
     * @type object
    */
    params: {
        /**
         * @type string
        */
        channel: NotificationTypeAParamsChannelEnumKey;
        /**
         * @type string
        */
        messageA: string;
    };
};