/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetPetsQueryLimit, GetPetsResponse } from './GetPets'

export function getPets(params?: { limit?: GetPetsQueryLimit }, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<GetPetsResponse> {
  return cy
    .request<GetPetsResponse>({
      method: 'GET',
      url: `${123456}/pets`,
      qs: params,
      ...options,
    })
    .then((res) => res.body)
}
