/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export function createPets(data: CreatePetsMutationRequest, options?: Partial<Cypress.RequestOptions>): Cypress.Chainable<CreatePetsMutationResponse> {
  return cy
    .request({
      method: 'post',
      url: '/pets',
      body: data,
      ...options,
    })
    .then((res: Cypress.Response<CreatePetsMutationResponse>) => res.body)
}
