/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export function deletePetsPetid(options?: Partial<Cypress.RequestOptions>): Cypress.Chainable<DeletePetsPetidMutationResponse> {
  return cy
    .request<DeletePetsPetidMutationResponse>({
      method: 'delete',
      url: `/pets/${petId}`,
      ...options,
    })
    .then((res) => res.body)
}
