/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export function listPets(options?: Partial<Cypress.RequestOptions>): Cypress.Chainable<ListPetsQueryResponse> {
  return cy
    .request({
      method: 'get',
      url: `${123456}/pets`,
      body: undefined,
      ...options,
    })
    .then((res: Cypress.Response<ListPetsQueryResponse>) => res.body)
}
