/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export function listPets(params?: ListPetsQueryParams, options?: Partial<Cypress.RequestOptions>): Cypress.Chainable<ListPetsResponseData> {
  return cy
    .request<ListPetsResponseData>({
      method: 'get',
      url: `${123456}/pets`,
      qs: params,
      ...options,
    })
    .then((res) => res.body)
}
