/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export function updatePet(petId: UpdatePet['petId'], data: UpdatePet, options?: Partial<Cypress.RequestOptions>): Cypress.Chainable<UpdatePet> {
  return cy
    .request<UpdatePet>({
      method: 'put',
      url: `/pets/${petId}`,
      body: data,
      ...options,
    })
    .then((res) => res.body)
}
