/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ListPetsQueryLimit = number

/**
 * @description A paged array of pets
 */
export type ListPetsStatus200 = object

/**
 * @description Unexpected error
 */
export type ListPetsStatusDefault = object

export type ListPetsRequestConfig = {
  /**
   * @type never | undefined
   */
  data?: never
  /**
   * @type never | undefined
   */
  pathParams?: never
  /**
   * @type object | undefined
   */
  queryParams?: {
    limit?: ListPetsQueryLimit
  }
  /**
   * @type never | undefined
   */
  headerParams?: never
  /**
   * @type string
   */
  url: '/pets'
}

export type ListPetsResponses = {
  '200': ListPetsStatus200
  default: ListPetsStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type ListPetsResponse = ListPetsStatus200 | ListPetsStatusDefault
