/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import * as z from 'zod'
import { item, itemTypeA, itemTypeB } from '../createItemUnionWithReadOnly'

/**
 * @description Success
 */
export const createItem200 = z.lazy(() => item)

/**
 * @description Item to create
 */
export const createItemMutationRequest = z.union([
  z
    .lazy(() => itemTypeA)
    .and(
      z.object({
        name: z.string(),
        type: z.literal('typeA'),
      }),
    ),
  z
    .lazy(() => itemTypeB)
    .and(
      z.object({
        name: z.string(),
        type: z.literal('typeB'),
      }),
    ),
])

export const createItemMutationResponse = z.lazy(() => createItem200)
