/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TestContent } from "./TestContent.ts";
import type { TestName } from "./TestName.ts";

export type CreateTestRequest = {
    content?: TestContent | null;
    name: TestName;
};