/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { userSchema } from "../userSchema.ts";

export const createUserStatusDefaultSchema = userSchema

export const createUserDataSchema = userSchema.optional().describe("Created user object")