/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'

/**
 * @type {object}
 */
export const petSchema = z.object({
  id: z.int(),
  name: z.string(),
  status: z.optional(z.string()),
  tags: z.optional(z.array(z.string())),
})
