/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/fetch'
import type { FindPetsByTagsQueryParams, FindPetsByTagsQueryResponse, FindPetsByTags400 } from './FindPetsByTags'
import type { InfiniteData, QueryKey, QueryClient, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult } from '@tanstack/react-query'
import { fetch } from './.kubb/fetch'
import { infiniteQueryOptions, useSuspenseInfiniteQuery } from '@tanstack/react-query'

export const findPetsByTagsSuspenseInfiniteQueryKey = (params: FindPetsByTagsQueryParams) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type FindPetsByTagsSuspenseInfiniteQueryKey = ReturnType<typeof findPetsByTagsSuspenseInfiniteQueryKey>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function findPetsByTagsSuspenseInfinite(params: FindPetsByTagsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindPetsByTagsQueryResponse, ResponseErrorConfig<FindPetsByTags400>, unknown>({
    method: 'GET',
    url: `/pet/findByTags`,
    params,
    ...requestConfig,
  })
}

export function findPetsByTagsSuspenseInfiniteQueryOptions(params: FindPetsByTagsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const queryKey = findPetsByTagsSuspenseInfiniteQueryKey(params)
  return infiniteQueryOptions<
    FindPetsByTagsQueryResponse,
    ResponseErrorConfig<FindPetsByTags400>,
    InfiniteData<FindPetsByTagsQueryResponse>,
    typeof queryKey,
    NonNullable<FindPetsByTagsQueryParams['pageSize']>
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      params = {
        ...(params ?? {}),
        ['pageSize']: pageParam as unknown as FindPetsByTagsQueryParams['pageSize'],
      } as FindPetsByTagsQueryParams
      return findPetsByTagsSuspenseInfinite(params, { ...config, signal: config.signal ?? signal })
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['cursor'],
    getPreviousPageParam: (firstPage) => firstPage['cursor'],
  })
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function useFindPetsByTagsSuspenseInfinite<
  TQueryFnData = FindPetsByTagsQueryResponse,
  TError = ResponseErrorConfig<FindPetsByTags400>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = FindPetsByTagsSuspenseInfiniteQueryKey,
  TPageParam = NonNullable<FindPetsByTagsQueryParams['pageSize']>,
>(
  params: FindPetsByTagsQueryParams,
  options: {
    query?: Partial<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? findPetsByTagsSuspenseInfiniteQueryKey(params)

  const query = useSuspenseInfiniteQuery(
    {
      ...findPetsByTagsSuspenseInfiniteQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
