/* eslint-disable no-alert, no-console */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import fetch from 'axios'
import type { RequestConfig, ResponseErrorConfig } from 'axios'

export function getImportPathUrl() {
  const res = { method: 'GET', url: `/pet/findByTags` as const }
  return res
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function importPath(params?: ImportPath, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ImportPath, ResponseErrorConfig<ImportPath>, unknown>({
    method: 'GET',
    url: getImportPathUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
