openapi: 3.0.3
info:
  title: Discriminator Any Of
  version: 1.0.0
components:
  schemas:
    # Base vehicle
    Vehicle:
      type: object
      properties:
        id:
          type: string
          description: Unique vehicle identifier
        type:
          type: string
          description: Type of the vehicle, used for discriminator
      required:
        - id
        - type

    # Specific vehicle types
    Sedan:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
      properties:
        type:
          type: string
          enum: [Sedan]
        seats:
          type: integer
          description: Number of seats

    SUV:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
      properties:
        type:
          type: string
          enum: [SUV]
        offroadCapability:
          type: boolean
          description: Can handle offroad terrain

    ElectricCar:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
      properties:
        type:
          type: string
          enum: [ElectricCar]
        batteryCapacity:
          type: number
          format: float
          description: Battery capacity in kWh

    # AnyOf example with discriminator
    Car:
      anyOf:
        - $ref: '#/components/schemas/Sedan'
        - $ref: '#/components/schemas/SUV'
      discriminator:
        propertyName: type
        mapping:
          Sedan: '#/components/schemas/Sedan'
          SUV: '#/components/schemas/SUV'

    # AnyOf including ElectricCar
    VehicleChoice:
      anyOf:
        - $ref: '#/components/schemas/Sedan'
        - $ref: '#/components/schemas/SUV'
        - $ref: '#/components/schemas/ElectricCar'
      discriminator:
        propertyName: type
        mapping:
          Sedan: '#/components/schemas/Sedan'
          SUV: '#/components/schemas/SUV'
          ElectricCar: '#/components/schemas/ElectricCar'
