/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type object
 */
export type Order = {
  /**
   * @example 10
   * @type integer | undefined
   */
  id: number | undefined
  /**
   * @example 198772
   * @type integer | undefined
   */
  petId: number | undefined
  /**
   * @type object | undefined
   */
  params:
    | {
        /**
         * @description Order Status
         * @example approved
         * @type string
         */
        status: 'placed' | 'approved' | 'delivered'
        /**
         * @type string
         */
        type: string
      }
    | undefined
  /**
   * @example 7
   * @type integer | undefined
   */
  quantity: number | undefined
  /**
   * @type string | undefined
   */
  shipDate: string | undefined
  /**
   * @description Order Status
   */
  status: ('accepted' | (string & {})) | undefined
  /**
   * @description HTTP Status
   * @example 200
   * @type number | undefined
   */
  http_status: (200 | 400 | 500) | undefined
  /**
   * @type boolean | undefined
   */
  complete: boolean | undefined
}

/**
 * @type object
 */
export type Address = {
  /**
   * @type string | undefined
   */
  streetName: string | undefined
  /**
   * @type string | undefined
   */
  streetNumber: string | undefined
  /**
   * @example Palo Alto
   * @type string | undefined
   */
  city: string | undefined
  /**
   * @example CA
   * @type string | undefined
   */
  state: string | undefined
  /**
   * @example 94301
   * @type string | undefined
   */
  zip: string | undefined
}

/**
 * @type object
 */
export type Customer = {
  /**
   * @example 100000
   * @type integer | undefined
   */
  id: number | undefined
  /**
   * @type object | undefined
   */
  params:
    | {
        /**
         * @description Order Status
         * @example approved
         * @type string
         */
        status: 'placed' | 'approved' | 'delivered'
        /**
         * @type string
         */
        type: string
      }
    | undefined
  /**
   * @example fehguy
   * @type string | undefined
   */
  username: string | undefined
  /**
   * @type array | undefined
   */
  address: Address[] | undefined
}

export type HappyCustomer = Customer & {
  /**
   * @type boolean | undefined
   */
  isHappy: true | undefined
}

export type UnhappyCustomer = Customer & {
  /**
   * @type string | undefined
   */
  reasonToBeUnhappy: string | undefined
  /**
   * @type boolean | undefined
   */
  isHappy: any | undefined
}

/**
 * @type object
 */
export type Category = {
  /**
   * @example 1
   * @type integer | undefined
   */
  id: number | undefined
  /**
   * @example Dogs
   * @type string | undefined
   */
  name: string | undefined
}

/**
 * @type object
 */
export type User = {
  /**
   * @example 10
   * @type integer | undefined
   */
  id: number | undefined
  /**
   * @example theUser
   * @type string | undefined
   */
  username: string | undefined
  /**
   * @example John
   * @type string | undefined
   */
  firstName: string | undefined
  /**
   * @example James
   * @type string | undefined
   */
  lastName: string | undefined
  /**
   * @example john@email.com
   * @type string | undefined
   */
  email: string | undefined
  /**
   * @example 12345
   * @type string | undefined
   */
  password: string | undefined
  /**
   * @example 12345
   * @type string | undefined
   */
  phone: string | undefined
  /**
   * @description User Status
   * @example 1
   * @type integer | undefined
   */
  userStatus: number | undefined
}

/**
 * @type object
 */
export type Tag = {
  /**
   * @type integer | undefined
   */
  id: number | undefined
  /**
   * @type string | undefined
   */
  name: string | undefined
}

/**
 * @type object
 */
export type Dog = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  readonly type: string | undefined
  /**
   * @type string | undefined
   */
  bark: string | undefined
}

/**
 * @type object
 */
export type Cat = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  readonly type: string | undefined
  /**
   * @type string | undefined
   */
  name: string | undefined
}

export type Pet = (
  | (Dog & {
      /**
       * @type string
       */
      readonly type: 'dog'
    })
  | (Cat & {
      /**
       * @type string
       */
      readonly type: 'cat'
    })
) & {
  /**
   * @example 10
   * @type integer | undefined
   */
  id: number | undefined
  /**
   * @type string
   */
  readonly type: 'dog' | 'cat'
  /**
   * @example doggie
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category: Category | undefined
  /**
   * @type array
   */
  photoUrls: string[]
  /**
   * @type array | undefined
   */
  readonly tags: Tag[] | undefined
  /**
   * @description pet status in the store
   * @type string | undefined
   */
  status: ('available' | 'pending' | 'sold') | undefined
}

export type FullAddress = Address & {
  /**
   * @type string
   */
  streetNumber: string
  /**
   * @type string
   */
  streetName: string
}

/**
 * @type object
 */
export type AddPetRequest = {
  /**
   * @example 10
   * @type integer | undefined
   */
  id: number | undefined
  /**
   * @example doggie
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category: Category | undefined
  /**
   * @type array
   */
  photoUrls: string[]
  /**
   * @type array | undefined
   */
  tags: Tag[] | undefined
  /**
   * @description pet status in the store
   * @type string | undefined
   */
  status: ('available' | 'pending' | 'sold' | 'in store') | undefined
}

/**
 * @type object
 */
export type ApiResponse = {
  /**
   * @type integer | undefined
   */
  code: number | undefined
  /**
   * @type string | undefined
   */
  type: string | undefined
  /**
   * @type string | undefined
   */
  message: string | undefined
}

/**
 * @type object
 */
export type PetNotFound = {
  /**
   * @type integer | undefined
   */
  code: number | undefined
  /**
   * @type string | undefined
   */
  message: string | undefined
}

/**
 * @type array
 */
export type UserArray = User[]

export type UpdatePetStatus200 = Pet

/**
 * @type any
 */
export type UpdatePetStatus400 = any

/**
 * @type any
 */
export type UpdatePetStatus404 = any

/**
 * @type any
 */
export type UpdatePetStatus405 = any

/**
 * @description Update an existent pet in the store
 */
export type UpdatePetData = Omit<NonNullable<Pet>, 'type' | 'tags'>

/**
 * @type object
 */
export type UpdatePetRequestConfig = {
  data: UpdatePetData | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/pet'
}

/**
 * @type object
 */
export type UpdatePetResponses = {
  '200': UpdatePetStatus200
  '400': UpdatePetStatus400
  '404': UpdatePetStatus404
  '405': UpdatePetStatus405
}

/**
 * @description Union of all possible responses
 */
export type UpdatePetResponse = UpdatePetStatus200 | UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405

export type AddPetStatus200 = Pet

/**
 * @type object
 */
export type AddPetStatus405 = {
  /**
   * @type integer | undefined
   */
  code: number | undefined
  /**
   * @type string | undefined
   */
  message: string | undefined
}

/**
 * @description Create a new pet in the store
 * @type object
 */
export type AddPetData = AddPetRequest

/**
 * @type object
 */
export type AddPetRequestConfig = {
  data: AddPetData | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/pet'
}

/**
 * @type object
 */
export type AddPetResponses = {
  '200': AddPetStatus200
  '405': AddPetStatus405
}

/**
 * @description Union of all possible responses
 */
export type AddPetResponse = AddPetStatus200 | AddPetStatus405

/**
 * @description Status values that need to be considered for filter
 * @default "available"
 * @type string | undefined
 */
export type FindPetsByStatusQueryStatus = ('available' | 'pending' | 'sold') | undefined

/**
 * @type array
 */
export type FindPetsByStatusStatus200 = Pet[]

/**
 * @type any
 */
export type FindPetsByStatusStatus400 = any

/**
 * @type object
 */
export type FindPetsByStatusRequestConfig = {
  data: never | undefined
  pathParams: never | undefined
  /**
   * @type object | undefined
   */
  queryParams:
    | {
        status: FindPetsByStatusQueryStatus | undefined
      }
    | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/pet/findByStatus'
}

/**
 * @type object
 */
export type FindPetsByStatusResponses = {
  '200': FindPetsByStatusStatus200
  '400': FindPetsByStatusStatus400
}

/**
 * @description Union of all possible responses
 */
export type FindPetsByStatusResponse = FindPetsByStatusStatus200 | FindPetsByStatusStatus400

/**
 * @description Tags to filter by
 * @type array | undefined
 */
export type FindPetsByTagsQueryTags = string[] | undefined

/**
 * @description to request with required page number or pagination
 * @type string | undefined
 */
export type FindPetsByTagsQueryPage = string | undefined

/**
 * @description to request with required page size
 * @type string | undefined
 */
export type FindPetsByTagsQueryPageSize = string | undefined

/**
 * @type array
 */
export type FindPetsByTagsStatus200 = Pet[]

/**
 * @type any
 */
export type FindPetsByTagsStatus400 = any

/**
 * @type object
 */
export type FindPetsByTagsRequestConfig = {
  data: never | undefined
  pathParams: never | undefined
  /**
   * @type object | undefined
   */
  queryParams:
    | {
        tags: FindPetsByTagsQueryTags | undefined
        page: FindPetsByTagsQueryPage | undefined
        pageSize: FindPetsByTagsQueryPageSize | undefined
      }
    | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/pet/findByTags'
}

/**
 * @type object
 */
export type FindPetsByTagsResponses = {
  '200': FindPetsByTagsStatus200
  '400': FindPetsByTagsStatus400
}

/**
 * @description Union of all possible responses
 */
export type FindPetsByTagsResponse = FindPetsByTagsStatus200 | FindPetsByTagsStatus400

/**
 * @description ID of pet to return
 * @type integer
 */
export type GetPetByIdPathPetId = number

export type GetPetByIdStatus200 = Pet

/**
 * @type any
 */
export type GetPetByIdStatus400 = any

/**
 * @type any
 */
export type GetPetByIdStatus404 = any

/**
 * @type object
 */
export type GetPetByIdRequestConfig = {
  data: never | undefined
  /**
   * @type object
   */
  pathParams: {
    petId: GetPetByIdPathPetId
  }
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/pet/${string}`
}

/**
 * @type object
 */
export type GetPetByIdResponses = {
  '200': GetPetByIdStatus200
  '400': GetPetByIdStatus400
  '404': GetPetByIdStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetPetByIdResponse = GetPetByIdStatus200 | GetPetByIdStatus400 | GetPetByIdStatus404

/**
 * @description ID of pet that needs to be updated
 * @type integer
 */
export type UpdatePetWithFormPathPetId = number

/**
 * @description Name of pet that needs to be updated
 * @type string | undefined
 */
export type UpdatePetWithFormQueryName = string | undefined

/**
 * @description Status of pet that needs to be updated
 * @type string | undefined
 */
export type UpdatePetWithFormQueryStatus = string | undefined

/**
 * @type any
 */
export type UpdatePetWithFormStatus405 = any

/**
 * @type object
 */
export type UpdatePetWithFormRequestConfig = {
  data: never | undefined
  /**
   * @type object
   */
  pathParams: {
    petId: UpdatePetWithFormPathPetId
  }
  /**
   * @type object | undefined
   */
  queryParams:
    | {
        name: UpdatePetWithFormQueryName | undefined
        status: UpdatePetWithFormQueryStatus | undefined
      }
    | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/pet/${string}`
}

/**
 * @type object
 */
export type UpdatePetWithFormResponses = {
  '405': UpdatePetWithFormStatus405
}

/**
 * @description Union of all possible responses
 */
export type UpdatePetWithFormResponse = UpdatePetWithFormStatus405

/**
 * @type string | undefined
 */
export type DeletePetHeaderApiKey = string | undefined

/**
 * @description Pet id to delete
 * @type integer
 */
export type DeletePetPathPetId = number

/**
 * @type array
 */
export type DeletePetStatus200 = ('TYPE1' | 'TYPE2' | 'TYPE3')[]

/**
 * @type any
 */
export type DeletePetStatus400 = any

/**
 * @type object
 */
export type DeletePetRequestConfig = {
  data: never | undefined
  /**
   * @type object
   */
  pathParams: {
    petId: DeletePetPathPetId
  }
  queryParams: never | undefined
  /**
   * @type object | undefined
   */
  headerParams:
    | {
        api_key: DeletePetHeaderApiKey | undefined
      }
    | undefined
  /**
   * @type string
   */
  url: `/pet/${string}`
}

/**
 * @type object
 */
export type DeletePetResponses = {
  '200': DeletePetStatus200
  '400': DeletePetStatus400
}

/**
 * @description Union of all possible responses
 */
export type DeletePetResponse = DeletePetStatus200 | DeletePetStatus400

/**
 * @description ID of pet to update
 * @type integer
 */
export type UploadFilePathPetId = number

/**
 * @description Additional Metadata
 * @type string | undefined
 */
export type UploadFileQueryAdditionalMetadata = string | undefined

/**
 * @type object
 */
export type UploadFileStatus200 = ApiResponse

/**
 * @type string | undefined
 */
export type UploadFileData = Blob | undefined

/**
 * @type object
 */
export type UploadFileRequestConfig = {
  data: UploadFileData | undefined
  /**
   * @type object
   */
  pathParams: {
    petId: UploadFilePathPetId
  }
  /**
   * @type object | undefined
   */
  queryParams:
    | {
        additionalMetadata: UploadFileQueryAdditionalMetadata | undefined
      }
    | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/pet/${string}/uploadImage`
}

/**
 * @type object
 */
export type UploadFileResponses = {
  '200': UploadFileStatus200
}

/**
 * @description Union of all possible responses
 */
export type UploadFileResponse = UploadFileStatus200

/**
 * @type object
 */
export type GetInventoryStatus200 = {
  [key: string]: number
}

/**
 * @type object
 */
export type GetInventoryRequestConfig = {
  data: never | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/store/inventory'
}

/**
 * @type object
 */
export type GetInventoryResponses = {
  '200': GetInventoryStatus200
}

/**
 * @description Union of all possible responses
 */
export type GetInventoryResponse = GetInventoryStatus200

/**
 * @type object
 */
export type PlaceOrderStatus200 = Order

/**
 * @type any
 */
export type PlaceOrderStatus405 = any

/**
 * @description Order description
 * @type object | undefined
 */
export type PlaceOrderData = Order | undefined

/**
 * @type object
 */
export type PlaceOrderRequestConfig = {
  data: PlaceOrderData | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/store/order'
}

/**
 * @type object
 */
export type PlaceOrderResponses = {
  '200': PlaceOrderStatus200
  '405': PlaceOrderStatus405
}

/**
 * @description Union of all possible responses
 */
export type PlaceOrderResponse = PlaceOrderStatus200 | PlaceOrderStatus405

/**
 * @type object
 */
export type PlaceOrderPatchStatus200 = Order

/**
 * @type any
 */
export type PlaceOrderPatchStatus405 = any

/**
 * @type object | undefined
 */
export type PlaceOrderPatchData = Order | undefined

/**
 * @type object
 */
export type PlaceOrderPatchRequestConfig = {
  data: PlaceOrderPatchData | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/store/order'
}

/**
 * @type object
 */
export type PlaceOrderPatchResponses = {
  '200': PlaceOrderPatchStatus200
  '405': PlaceOrderPatchStatus405
}

/**
 * @description Union of all possible responses
 */
export type PlaceOrderPatchResponse = PlaceOrderPatchStatus200 | PlaceOrderPatchStatus405

/**
 * @description ID of order that needs to be fetched
 * @type integer
 */
export type GetOrderByIdPathOrderId = number

/**
 * @type object
 */
export type GetOrderByIdStatus200 = Order

/**
 * @type any
 */
export type GetOrderByIdStatus400 = any

/**
 * @type any
 */
export type GetOrderByIdStatus404 = any

/**
 * @type object
 */
export type GetOrderByIdRequestConfig = {
  data: never | undefined
  /**
   * @type object
   */
  pathParams: {
    orderId: GetOrderByIdPathOrderId
  }
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/store/order/${string}`
}

/**
 * @type object
 */
export type GetOrderByIdResponses = {
  '200': GetOrderByIdStatus200
  '400': GetOrderByIdStatus400
  '404': GetOrderByIdStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetOrderByIdResponse = GetOrderByIdStatus200 | GetOrderByIdStatus400 | GetOrderByIdStatus404

/**
 * @description ID of the order that needs to be deleted
 * @type integer
 */
export type DeleteOrderPathOrderId = number

/**
 * @type any
 */
export type DeleteOrderStatus400 = any

/**
 * @type any
 */
export type DeleteOrderStatus404 = any

/**
 * @type object
 */
export type DeleteOrderRequestConfig = {
  data: never | undefined
  /**
   * @type object
   */
  pathParams: {
    orderId: DeleteOrderPathOrderId
  }
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/store/order/${string}`
}

/**
 * @type object
 */
export type DeleteOrderResponses = {
  '400': DeleteOrderStatus400
  '404': DeleteOrderStatus404
}

/**
 * @description Union of all possible responses
 */
export type DeleteOrderResponse = DeleteOrderStatus400 | DeleteOrderStatus404

/**
 * @type object
 */
export type CreateUserStatusDefault = User

/**
 * @description Created user object
 * @type object | undefined
 */
export type CreateUserData = User | undefined

/**
 * @type object
 */
export type CreateUserRequestConfig = {
  data: CreateUserData | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/user'
}

/**
 * @type object
 */
export type CreateUserResponses = {
  default: CreateUserStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type CreateUserResponse = CreateUserStatusDefault

/**
 * @type object
 */
export type CreateUsersWithListInputStatus200 = User

/**
 * @type any
 */
export type CreateUsersWithListInputStatusDefault = any

/**
 * @type array | undefined
 */
export type CreateUsersWithListInputData = User[] | undefined

/**
 * @type object
 */
export type CreateUsersWithListInputRequestConfig = {
  data: CreateUsersWithListInputData | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/user/createWithList'
}

/**
 * @type object
 */
export type CreateUsersWithListInputResponses = {
  '200': CreateUsersWithListInputStatus200
  default: CreateUsersWithListInputStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type CreateUsersWithListInputResponse = CreateUsersWithListInputStatus200 | CreateUsersWithListInputStatusDefault

/**
 * @description The user name for login
 * @type string | undefined
 */
export type LoginUserQueryUsername = string | undefined

/**
 * @description The password for login in clear text
 * @type string | undefined
 */
export type LoginUserQueryPassword = string | undefined

/**
 * @type string
 */
export type LoginUserStatus200 = string

/**
 * @type any
 */
export type LoginUserStatus400 = any

/**
 * @type object
 */
export type LoginUserRequestConfig = {
  data: never | undefined
  pathParams: never | undefined
  /**
   * @type object | undefined
   */
  queryParams:
    | {
        username: LoginUserQueryUsername | undefined
        password: LoginUserQueryPassword | undefined
      }
    | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/user/login'
}

/**
 * @type object
 */
export type LoginUserResponses = {
  '200': LoginUserStatus200
  '400': LoginUserStatus400
}

/**
 * @description Union of all possible responses
 */
export type LoginUserResponse = LoginUserStatus200 | LoginUserStatus400

/**
 * @type any
 */
export type LogoutUserStatusDefault = any

/**
 * @type object
 */
export type LogoutUserRequestConfig = {
  data: never | undefined
  pathParams: never | undefined
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: '/user/logout'
}

/**
 * @type object
 */
export type LogoutUserResponses = {
  default: LogoutUserStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type LogoutUserResponse = LogoutUserStatusDefault

/**
 * @description The name that needs to be fetched. Use user1 for testing.
 * @type string
 */
export type GetUserByNamePathUsername = string

/**
 * @type object
 */
export type GetUserByNameStatus200 = User

/**
 * @type any
 */
export type GetUserByNameStatus400 = any

/**
 * @type any
 */
export type GetUserByNameStatus404 = any

/**
 * @type object
 */
export type GetUserByNameRequestConfig = {
  data: never | undefined
  /**
   * @type object
   */
  pathParams: {
    username: GetUserByNamePathUsername
  }
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/user/${string}`
}

/**
 * @type object
 */
export type GetUserByNameResponses = {
  '200': GetUserByNameStatus200
  '400': GetUserByNameStatus400
  '404': GetUserByNameStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetUserByNameResponse = GetUserByNameStatus200 | GetUserByNameStatus400 | GetUserByNameStatus404

/**
 * @description name that need to be deleted
 * @type string
 */
export type UpdateUserPathUsername = string

/**
 * @type any
 */
export type UpdateUserStatusDefault = any

/**
 * @description Update an existent user in the store
 * @type object | undefined
 */
export type UpdateUserData = User | undefined

/**
 * @type object
 */
export type UpdateUserRequestConfig = {
  data: UpdateUserData | undefined
  /**
   * @type object
   */
  pathParams: {
    username: UpdateUserPathUsername
  }
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/user/${string}`
}

/**
 * @type object
 */
export type UpdateUserResponses = {
  default: UpdateUserStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type UpdateUserResponse = UpdateUserStatusDefault

/**
 * @description The name that needs to be deleted
 * @type string
 */
export type DeleteUserPathUsername = string | null

/**
 * @type any
 */
export type DeleteUserStatus400 = any

/**
 * @type any
 */
export type DeleteUserStatus404 = any

/**
 * @type object
 */
export type DeleteUserRequestConfig = {
  data: never | undefined
  /**
   * @type object
   */
  pathParams: {
    username: DeleteUserPathUsername
  }
  queryParams: never | undefined
  headerParams: never | undefined
  /**
   * @type string
   */
  url: `/user/${string}`
}

/**
 * @type object
 */
export type DeleteUserResponses = {
  '400': DeleteUserStatus400
  '404': DeleteUserStatus404
}

/**
 * @description Union of all possible responses
 */
export type DeleteUserResponse = DeleteUserStatus400 | DeleteUserStatus404
