/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from '../Error.ts'
import type { TaxLot } from '../TaxLot.ts'

export type FindTaxLotByBblPathParams = {
  /**
   * @description The ten character code compromised of a one character borough, five character block, and four character lot codes.
   * @pattern ^([0-9]{10})$
   * @example 1000477501
   * @type string
   */
  bbl: string
}

/**
 * @description A tax lot object
 */
export type FindTaxLotByBbl200 = TaxLot

/**
 * @description Invalid client request
 */
export type FindTaxLotByBbl400 = Error

/**
 * @description Requested resource does not exist or is not available
 */
export type FindTaxLotByBbl404 = Error

/**
 * @description Server side error
 */
export type FindTaxLotByBbl500 = Error

export type FindTaxLotByBblQuery = {
  Response: FindTaxLotByBbl200
  PathParams: FindTaxLotByBblPathParams
  Errors: FindTaxLotByBbl400 | FindTaxLotByBbl404 | FindTaxLotByBbl500
}

export type FindTaxLotByBblQueryResponse = FindTaxLotByBbl200
