/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetPetsQueryPageSize, GetPetsHeaderXApiKey, GetPetsResponse } from './GetPets'

export function getPets(
  headers: { xApiKey: GetPetsHeaderXApiKey },
  params?: { pageSize?: GetPetsQueryPageSize },
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<GetPetsResponse> {
  return cy
    .request<GetPetsResponse>({
      method: 'GET',
      url: `/pets`,
      qs: params ? { page_size: params.pageSize } : undefined,
      headers: headers ? { 'x-api-key': headers.xApiKey } : undefined,
      ...options,
    })
    .then((res) => res.body)
}
