/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const findPetsByStatusQueryParamsStatusEnum = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type FindPetsByStatusQueryParamsStatusEnumKey = (typeof findPetsByStatusQueryParamsStatusEnum)[keyof typeof findPetsByStatusQueryParamsStatusEnum]

export type FindPetsByStatusQueryParams = {
  /**
   * @type string | undefined
   */
  status?: FindPetsByStatusQueryParamsStatusEnumKey
}

/**
 * @description Successful operation
 */
export type FindPetsByStatus200 = object

export type FindPetsByStatusQueryResponse = FindPetsByStatus200

export type FindPetsByStatusQuery = {
  Response: FindPetsByStatus200
  QueryParams: FindPetsByStatusQueryParams
  Errors: any
}
