/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const listPetsQueryLimitSchema = z.int().optional()

export const listPetsStatus200Schema = z.object({})

export const listPetsStatusDefaultSchema = z.object({})
