/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const listPetsQueryLimitSchemaSchema = z.int().optional()

/**
 * @description A paged array of pets
 */
export const listPetsStatus200SchemaSchema = z.object({})

/**
 * @description Unexpected error
 */
export const listPetsStatusDefaultSchemaSchema = z.object({})
