/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "../../zod.ts";

export const userArraySchema = z.any().describe("List of user object");

export type UserArraySchema = z.infer<typeof userArraySchema>;
