/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { category } from '../petQuestionToken'

export type Pet = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  tag?: string
  /**
   * @type object | undefined
   */
  category?: category
}
