openapi: 3.0.3
info:
  title: Category
  version: 1.0.0
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
