openapi: 3.0.3
info:
  title: Repro Shared Definitions
  version: v1.0
components:
  schemas:
    Parcel:
      type: object
      properties:
        parcelNo:
          type: string
        trackingNumber:
          type: string

    ContactDetailsType:
      type: object
      properties:
        fullName:
          type: string
        emailAddress:
          type: string
      required:
        - fullName
        - emailAddress

    ProductDetails:
      type: object
      properties:
        productCount:
          type: number
        itemIds:
          type: array
          items:
            type: string
      required:
        - itemIds

    TypeARequest:
      type: object
      properties:
        actorId:
          type: string
        contactDetails:
          $ref: "#/components/schemas/ContactDetailsType"
        productDetails:
          $ref: "#/components/schemas/ProductDetails"
      required:
        - actorId
        - contactDetails
        - productDetails

    TypeBRequest:
      type: object
      properties:
        actorId:
          type: string
        ticketId:
          type: string
        contactDetails:
          $ref: "#/components/schemas/ContactDetailsType"
      required:
        - actorId
        - ticketId
        - contactDetails

    Result:
      type: object
      properties:
        returnId:
          type: string
        state:
          type: string
          enum:
            - ACCEPTED
            - REJECTED
        parcels:
          type: array
          items:
            $ref: "#/components/schemas/Parcel"
      required:
        - returnId
        - state

  requestBodies:
    RequestABody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TypeARequest"

    RequestBBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TypeBRequest"

  responses:
    createReturnResponse:
      description: Shared create-return response.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Result"
