openapi: 3.0.3
info:
  title: PetStore with external file ref
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          $ref: './category.yaml#/components/schemas/Category'
