/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeletePetPathParams = {
  petId: string
}

export const deletePet200Enum = {
  TYPE1: 'TYPE1',
  TYPE2: 'TYPE2',
  TYPE3: 'TYPE3',
} as const

export type DeletePet200EnumKey = (typeof deletePet200Enum)[keyof typeof deletePet200Enum]

/**
 * @description Successful deletion
 */
export type DeletePet200 = DeletePet200EnumKey[]

export type DeletePetMutation = {
  Response: DeletePet200
  Errors: any
}

export type DeletePetMutationResponse = DeletePet200
