/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const createPetsPathParamsSchema = z.object({
  pet_id: z.string(),
})

export const createPetsQueryParamsSchema = z
  .object({
    include_deleted: z.boolean().optional(),
  })
  .optional()

export const createPetsHeaderParamsSchema = z.object({
  'X-EXAMPLE': z.enum(['ONE', 'TWO', 'THREE']),
})

/**
 * @description Null response
 */
export const createPets201Schema = z.void()

export const createPetsMutationResponseSchema = createPets201Schema

export const createPetsMutationSchema = z.object({
  Response: createPets201Schema,
  QueryParams: createPetsQueryParamsSchema,
  PathParams: createPetsPathParamsSchema,
  HeaderParams: createPetsHeaderParamsSchema,
  Errors: z.any(),
})
