/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const petSchema = z.object({
  id: z.coerce.number().int(),
  name: z.coerce.string(),
  status: z.coerce.string().optional(),
  tags: z.array(z.coerce.string()).optional(),
})
