export type CallToolResult = {
  content: Array<{ type: 'text'; text: string }>
  isError?: boolean
  _meta?: Record<string, unknown>
}

export const NotifyTypes = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  WARN: 'WARN',
  PLUGIN_START: 'PLUGIN_START',
  PLUGIN_END: 'PLUGIN_END',
  FILES_START: 'FILES_START',
  FILE_UPDATE: 'FILE_UPDATE',
  FILES_END: 'FILES_END',
  GENERATION_START: 'GENERATION_START',
  GENERATION_END: 'GENERATION_END',
  CONFIG_LOADED: 'CONFIG_LOADED',
  CONFIG_ERROR: 'CONFIG_ERROR',
  CONFIG_READY: 'CONFIG_READY',
  SETUP_START: 'SETUP_START',
  SETUP_END: 'SETUP_END',
  BUILD_START: 'BUILD_START',
  BUILD_END: 'BUILD_END',
  BUILD_FAILED: 'BUILD_FAILED',
  BUILD_SUCCESS: 'BUILD_SUCCESS',
  FATAL_ERROR: 'FATAL_ERROR',
} as const
