/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const orderStatus = {
  IN_PROGRESS: 'in_progress',
  AWAITING_PAYMENT: 'awaiting_payment',
  FULLY_SHIPPED: 'fully_shipped',
} as const

export type OrderStatusKey = (typeof orderStatus)[keyof typeof orderStatus]
