/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { category } from '../petMapper'

export type Pet = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  tag?: string
  category?: string
}
 * @type object | undefined
   */
  category: category | undefined
}
