/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteOrderPathParams,
  DeleteOrderMutationResponse,
} from "../models.ts";

export function deleteOrder(
  orderId: DeleteOrderPathParams["orderId"],
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<DeleteOrderMutationResponse> {
  return cy
    .request<DeleteOrderMutationResponse>({
      method: "DELETE",
      url: `http://localhost:3000/store/order/${orderId}`,
      ...options,
    })
    .then((res) => res.body);
}
