/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { HttpResponseResolver } from 'msw'
import { http } from 'msw'

export function deletePetsPetid(data?: string | number | boolean | null | object | HttpResponseResolver<never, never, DeletePetsPetidMutationResponse>) {
  return http.delete<never, never, DeletePetsPetidMutationResponse>('/pets/:petId', function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
    })
  })
}
