/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { HttpResponseResolver } from 'msw'
import { http } from 'msw'

export function listPetsResponse200(data: ListPetsQueryResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function listPetsResponse400(data?: ListPets400) {
  return new Response(JSON.stringify(data), {
    status: 400,
  })
}

export function listPets(data?: ListPetsQueryResponse | HttpResponseResolver<never, never, ListPetsQueryResponse>) {
  return http.get<never, never, ListPetsQueryResponse>('/pets', function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
