/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import { http } from 'msw'

export function getPetsTemplateBaseUrlResponse200(data: GetPetsTemplateBaseUrl) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function getPetsTemplateBaseUrlResponse400(data?: GetPetsTemplateBaseUrl) {
  return new Response(JSON.stringify(data), {
    status: 400,
  })
}

export function getPetsTemplateBaseUrl(
  data?: GetPetsTemplateBaseUrl | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Response | Promise<Response>),
) {
  return http.get(`${123456}/pets`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
