/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const enumAllOfReasonEnum = {
  created_at: 'created_at',
  description: 'description',
} as const

export type EnumAllOfReasonEnumKey = (typeof enumAllOfReasonEnum)[keyof typeof enumAllOfReasonEnum]

export type EnumAllOf = {
  /**
   * @type string | undefined
   */
  reason?: EnumAllOfReasonEnumKey
}
