openapi: 3.0.3
info:
  title: Example spec
  version: 1.0.0
paths:
  /organizations/{organization-id}:
    get:
      summary: /organizations/{organization-id}
      tags:
        - Organizations
      operationId: getOrganizationById
      description: Retrieves detailed information about an organization by ID.
      parameters:
        - name: organization-id
          in: path
          description: Unique identifier for the organization
          required: true
          schema:
            type: string
            format: uuid
            example: "1397bb88-7985-4ed1-8b97-9bf05470a31c"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - message
                  - data
                properties:
                  status:
                    type: string
                    description: Status of the request
                    example: "success"
                  message:
                    type: string
                    description: Descriptive message about the result
                    example: "Request was successful."
                  data:
                    type: object
                    required:
                      - id
                      - name
                    properties:
                      id:
                        type: string
                        description: Unique identifier for the organization
                        format: uuid
                        example: "bef6d36f-6e75-414f-8f1e-29f853dfd045"
                      name:
                        type: string
                        description: Name of the organization
                        example: "Organization name"
