openapi: 3.0.3
info:
  title: Example spec
  version: 1.0.0
paths:
  /v1/items/{item_id}:
    get:
      summary: Get Item
      tags:
        - Items
      operationId: getItem
      description: Retrieves an item by ID.
      parameters:
        - name: item_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
