info:
  title: anyof test cases
  version: 1.0.0
openapi: 3.1.0
paths: {}
components:
  schemas:
    test:
      anyOf:
        - type: object
          properties:
            propertyA:
              type: string
          required:
            - propertyA
        - type: object
          properties:
            propertyA:
              type: string
            propertyB:
              type: string
          required:
            - propertyA
            - propertyB
