info:
  title: const test cases
  version: 1.0.0
openapi: 3.1.0
paths: {}
components:
  schemas:
    UuidSchema:
      type: string
      format: uuid
    NullableString:
      type:
        - string
        - "null"
    NullableStringWithAnyOf:
      anyOf:
        - type: string
        - type: "null"
    NullableStringUuid:
      type:
        - string
        - "null"
      format: uuid
    NullConst:
      required: true
      const: null
      description: |
        The value of this keyword MAY be null.
        Use of this keyword is functionally equivalent to an "enum" (Section 6.1.2) with a single value.
        An instance validates successfully against this keyword if its value is equal to the value of the keyword.
    StringValueConst:
      description: its value is equal to the value of the keyword
      required:
        - foobar
      properties:
        foobar:
          const: "foobar"
    NumberValueConst:
      description: its value is equal to the value of the keyword
      required:
        - foobar
      properties:
        foobar:
          const: 42
    MixedValueTypeConst:
      description: This probably should fail miserably
      required:
      - foobar
      properties:
        foobar:
          const: "foobar"
          type: number
