info:
  title: oneof test cases
  version: 1.0.0
openapi: 3.1.0
paths: {}
components:
  schemas:
    test:
      oneOf:
        - type: object
          properties:
            propertyA:
              type: string
        - type: object
          properties:
            propertyA:
              type: string
