import path from 'node:path'
import type { RootNode } from '@kubb/ast/types'
import type { KubbFile } from '@kubb/fabric-core/types'
import { useFabric } from '@kubb/react-fabric'
import type { GetFileOptions, PluginDriver } from '../PluginDriver.ts'
import type { Config, Plugin, PluginFactoryOptions, ResolveNameParams, ResolvePathParams } from '../types.ts'

type ResolvePathOptions = {
  pluginName?: string
  group?: {
    tag?: string
    path?: string
  }
  type?: ResolveNameParams['type']
}

type UseKubbReturn<TOptions extends PluginFactoryOptions = PluginFactoryOptions> = {
  plugin: Plugin<TOptions>
  mode: KubbFile.Mode
  config: Config
  /**
   * Returns the plugin whose `name` matches `pluginName`, defaulting to the current plugin.
   */
  getPluginByName: (pluginName?: string) => Plugin | undefined
  /**
   * Resolves a file reference, defaulting `pluginName` to the current plugin.
   */
  getFile: (params: Omit<GetFileOptions<ResolvePathOptions>, 'pluginName'> & { pluginName?: string }) => KubbFile.File<{ pluginName: string }>
  /**
   * Resolves a name, defaulting `pluginName` to the current plugin.
   */
  resolveName: (params: Omit<ResolveNameParams, 'pluginName'> & { pluginName?: string }) => string
  /**
   * Resolves a path, defaulting `pluginName` to the current plugin.
   */
  resolvePath: <TPathOptions = object>(params: Omit<ResolvePathParams<TPathOptions>, 'pluginName'> & { pluginName?: string }) => KubbFile.Path
  /**
   * Resolves the banner using the plugin's `output.banner` option.
   * Falls back to the default "Generated by Kubb" banner when `output.banner` is unset.
   * When `output.banner` is a function and no node is provided, returns the default banner.
   */
  resolveBanner: (node?: RootNode) => string | undefined
  /**
   * Resolves the footer using the plugin's `output.footer` option.
   * Returns `undefined` when no footer is configured.
   * When `output.footer` is a function and no node is provided, returns `undefined`.
   */
  resolveFooter: (node?: RootNode) => string | undefined
}

/**
 * Generates the default "Generated by Kubb" banner from node metadata.
 */
function buildDefaultBanner({ title, description, version, config }: { title?: string; description?: string; version?: string; config: Config }): string {
  try {
    let source = ''
    if (Array.isArray(config.input)) {
      const first = config.input[0]
      if (first && 'path' in first) {
        source = path.basename(first.path)
      }
    } else if ('path' in config.input) {
      source = path.basename(config.input.path)
    } else if ('data' in config.input) {
      source = 'text content'
    }

    let banner = '/**\n* Generated by Kubb (https://kubb.dev/).\n* Do not edit manually.\n'

    if (config.output.defaultBanner === 'simple') {
      banner += '*/\n'
      return banner
    }

    if (source) {
      banner += `* Source: ${source}\n`
    }

    if (title) {
      banner += `* Title: ${title}\n`
    }

    if (description) {
      const formattedDescription = description.replace(/\n/gm, '\n* ')
      banner += `* Description: ${formattedDescription}\n`
    }

    if (version) {
      banner += `* OpenAPI spec version: ${version}\n`
    }

    banner += '*/\n'
    return banner
  } catch (_error) {
    return '/**\n* Generated by Kubb (https://kubb.dev/).\n* Do not edit manually.\n*/'
  }
}

export function useKubb<TOptions extends PluginFactoryOptions = PluginFactoryOptions>(): UseKubbReturn<TOptions> {
  const { meta } = useFabric<{
    plugin: Plugin<TOptions>
    mode: KubbFile.Mode
    driver: PluginDriver
  }>()

  const config = meta.driver.config
  const defaultPluginName = meta.plugin.name

  const output = (
    meta.plugin.options as { output?: { banner?: string | ((node: RootNode) => string); footer?: string | ((node: RootNode) => string) } } | undefined
  )?.output

  return {
    plugin: meta.plugin as Plugin<TOptions>,
    mode: meta.mode,
    config,
    getPluginByName: (pluginName = defaultPluginName) => meta.driver.getPluginByName.call(meta.driver, pluginName),
    getFile: ({ pluginName = defaultPluginName, ...rest }) => meta.driver.getFile.call(meta.driver, { pluginName, ...rest }),
    resolveName: ({ pluginName = defaultPluginName, ...rest }) => meta.driver.resolveName.call(meta.driver, { pluginName, ...rest }),
    resolvePath: ({ pluginName = defaultPluginName, ...rest }) => meta.driver.resolvePath.call(meta.driver, { pluginName, ...rest }),
    resolveBanner: (node?: RootNode) => {
      if (typeof output?.banner === 'function') {
        return node ? output.banner(node) : buildDefaultBanner({ config })
      }
      if (typeof output?.banner === 'string') {
        return output.banner
      }
      return buildDefaultBanner({ config })
    },
    resolveFooter: (node?: RootNode) => {
      if (typeof output?.footer === 'function') {
        return node ? output.footer(node) : undefined
      }
      if (typeof output?.footer === 'string') {
        return output.footer
      }
      return undefined
    },
  }
}
