import type { RootNode } from '@kubb/ast/types'
import { beforeEach, describe, expect, test, vi } from 'vitest'
import { createMockedPluginDriver } from '../../../../configs/mocks.ts'
import type { Plugin } from '../types.ts'

const mockedPluginDriver = createMockedPluginDriver()

const mockedPlugin = { options: {} } as Plugin

vi.mock('@kubb/react-fabric', () => ({
  useFabric: vi.fn(),
}))

import { useFabric } from '@kubb/react-fabric'
import { useKubb } from './useKubb.ts'

const mockRootNode: RootNode = {
  kind: 'Root',
  schemas: [],
  operations: [],
  meta: { title: 'Pet Store', description: 'A sample API', version: '1.0.0' },
}

describe('useKubb', () => {
  beforeEach(() => {
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: mockedPlugin,
        mode: 'split',
        driver: mockedPluginDriver,
      },
    })
  })

  test('returns plugin from context meta', () => {
    const { plugin } = useKubb()

    expect(plugin).toBe(mockedPlugin)
  })

  test('returns mode from context meta', () => {
    const { mode } = useKubb()

    expect(mode).toBe('split')
  })

  test('returns config from pluginDriver', () => {
    const { config } = useKubb()

    expect(config).toBe(mockedPluginDriver.config)
  })

  test('exposes bound pluginDriver methods as top-level', () => {
    const result = useKubb()

    expect(typeof result.resolveName).toBe('function')
    expect(typeof result.resolvePath).toBe('function')
    expect(typeof result.getFile).toBe('function')
    expect(typeof result.getPluginByName).toBe('function')
  })

  test('respects mode set to single', () => {
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: mockedPlugin,
        mode: 'single',
        driver: mockedPluginDriver,
      },
    })
    const { mode } = useKubb()

    expect(mode).toBe('single')
  })
})

describe('resolveBanner', () => {
  test('returns default banner when no banner option is set', () => {
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: { plugin: { options: {} } as Plugin, mode: 'split', driver: mockedPluginDriver },
    })
    const { resolveBanner } = useKubb()

    expect(resolveBanner()).toContain('Generated by Kubb')
  })

  test('returns static string banner when output.banner is a string', () => {
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: { options: { output: { banner: '// my custom banner' } } } as unknown as Plugin,
        mode: 'split',
        driver: mockedPluginDriver,
      },
    })
    const { resolveBanner } = useKubb()

    expect(resolveBanner()).toBe('// my custom banner')
  })

  test('calls banner function with node when both are provided', () => {
    const bannerFn = vi.fn().mockReturnValue('// dynamic banner')
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: { options: { output: { banner: bannerFn } } } as unknown as Plugin,
        mode: 'split',
        driver: mockedPluginDriver,
      },
    })
    const { resolveBanner } = useKubb()
    const result = resolveBanner(mockRootNode)

    expect(bannerFn).toHaveBeenCalledWith(mockRootNode)
    expect(result).toBe('// dynamic banner')
  })

  test('returns default banner when banner is a function but no node is provided', () => {
    const bannerFn = vi.fn()
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: { options: { output: { banner: bannerFn } } } as unknown as Plugin,
        mode: 'split',
        driver: mockedPluginDriver,
      },
    })
    const { resolveBanner } = useKubb()
    const result = resolveBanner()

    expect(bannerFn).not.toHaveBeenCalled()
    expect(result).toContain('Generated by Kubb')
  })

  test('returns undefined when defaultBanner is false and no banner option is set', () => {
    const driver = createMockedPluginDriver({
      config: { root: '.', input: { path: 'spec.yaml' }, output: { path: './out', defaultBanner: false } },
    })
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: { plugin: { options: {} } as Plugin, mode: 'split', driver },
    })
    const { resolveBanner } = useKubb()

    expect(resolveBanner()).toBeNull()
  })

  test('returns simple banner when defaultBanner is "simple"', () => {
    const driver = createMockedPluginDriver({
      config: { root: '.', input: { path: 'spec.yaml' }, output: { path: './out', defaultBanner: 'simple' } },
    })
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: { plugin: { options: {} } as Plugin, mode: 'split', driver },
    })
    const { resolveBanner } = useKubb()
    const result = resolveBanner()

    expect(result).toContain('Generated by Kubb')
    expect(result).not.toContain('Source:')
    expect(result).not.toContain('Title:')
  })

  test('includes source filename in default banner when input.path is set', () => {
    const driver = createMockedPluginDriver({
      config: { root: '.', input: { path: '/specs/petstore.yaml' }, output: { path: './out' } },
    })
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: { plugin: { options: {} } as Plugin, mode: 'split', driver },
    })
    const { resolveBanner } = useKubb()
    const result = resolveBanner()

    expect(result).toContain('Source: petstore.yaml')
  })

  test('includes "text content" in default banner when input.data is set', () => {
    const driver = createMockedPluginDriver({
      config: { root: '.', input: { data: 'openapi: 3.0.0' }, output: { path: './out' } },
    })
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: { plugin: { options: {} } as Plugin, mode: 'split', driver },
    })
    const { resolveBanner } = useKubb()
    const result = resolveBanner()

    expect(result).toContain('Source: text content')
  })
})

describe('resolveFooter', () => {
  test('returns undefined when no footer option is set', () => {
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: { plugin: { options: {} } as Plugin, mode: 'split', driver: mockedPluginDriver },
    })
    const { resolveFooter } = useKubb()

    expect(resolveFooter()).toBeNull()
  })

  test('returns static string footer when output.footer is a string', () => {
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: { options: { output: { footer: '// end of file' } } } as unknown as Plugin,
        mode: 'split',
        driver: mockedPluginDriver,
      },
    })
    const { resolveFooter } = useKubb()

    expect(resolveFooter()).toBe('// end of file')
  })

  test('calls footer function with node when both are provided', () => {
    const footerFn = vi.fn().mockReturnValue('// dynamic footer')
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: { options: { output: { footer: footerFn } } } as unknown as Plugin,
        mode: 'split',
        driver: mockedPluginDriver,
      },
    })
    const { resolveFooter } = useKubb()
    const result = resolveFooter(mockRootNode)

    expect(footerFn).toHaveBeenCalledWith(mockRootNode)
    expect(result).toBe('// dynamic footer')
  })

  test('returns undefined when footer is a function but no node is provided', () => {
    const footerFn = vi.fn()
    vi.mocked(useFabric).mockReturnValue({
      exit: vi.fn(),
      meta: {
        plugin: { options: { output: { footer: footerFn } } } as unknown as Plugin,
        mode: 'split',
        driver: mockedPluginDriver,
      },
    })
    const { resolveFooter } = useKubb()
    const result = resolveFooter()

    expect(footerFn).not.toHaveBeenCalled()
    expect(result).toBeNull()
  })
})
