/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { showPetByIdHandler } from './showPetById'
import { showPetByIdPathPetIdSchema, showPetByIdStatus200Schema } from './showPetByIdSchema'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio'

server.registerTool(
  'showPetById',
  {
    description: 'Make a GET request to /pets/{petId}',
    outputSchema: { data: showPetByIdStatus200Schema },
    inputSchema: { petId: showPetByIdPathPetIdSchema },
  },
  async ({ petId }) => {
    return showPetByIdHandler({ petId })
  },
)
