/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { showPetByIdHandler } from './showPetById'
import { showPetByIdPathPetIdSchema, showPetByIdStatus200Schema } from './showPetByIdSchema'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio'

export const server = new McpServer({
  name: 'server',
  version: '0.0.0',
})

server.registerTool(
  'showPetById',
  {
    description: 'Make a GET request to /pets/{petId}',
    outputSchema: { data: showPetByIdStatus200Schema },
    inputSchema: { petId: showPetByIdPathPetIdSchema },
  },
  async ({ petId }) => {
    return showPetByIdHandler({ petId })
  },
)

export async function startServer() {
  try {
    const transport = new StdioServerTransport()
    await server.connect(transport)
  } catch (error) {
    console.error('Failed to start server:', error)
    process.exit(1)
  }
}
