/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const orderStatusEnum4 = {
  placed: 'placed',
  approved: 'approved',
  delivered: 'delivered',
} as const

export type OrderStatusEnum4Key = (typeof orderStatusEnum4)[keyof typeof orderStatusEnum4]

export const orderHttpStatusEnum4 = {
  '200': 200,
  '400': 400,
  '500': 500,
} as const

export type OrderHttpStatusEnum4Key = (typeof orderHttpStatusEnum4)[keyof typeof orderHttpStatusEnum4]

export type Order = {
  /**
   * @type integer | undefined, int64
   */
  id?: number
  /**
   * @type integer | undefined, int64
   */
  petId?: number
  /**
   * @type integer | undefined, int32
   */
  quantity?: number
  /**
   * @type string | undefined, date-time
   */
  shipDate?: Date
  /**
   * @description Order Status
   * @type string | undefined
   */
  status?: OrderStatusEnum4Key
  /**
   * @description HTTP Status
   * @type number | undefined
   */
  http_status?: OrderHttpStatusEnum4Key
  /**
   * @type boolean | undefined
   */
  complete?: boolean
}
