/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from '../Error.ts'
import type { ZoningDistrictClass } from '../ZoningDistrictClass.ts'

export type FindZoningDistrictClassByZoningDistrictClassIdPathParams = {
  /**
   * @pattern ^[A-z][0-9]+$
   * @type string
   */
  id: string
}

/**
 * @description A class schema for a zoning district
 */
export type FindZoningDistrictClassByZoningDistrictClassId200 = ZoningDistrictClass

/**
 * @description Invalid client request
 */
export type FindZoningDistrictClassByZoningDistrictClassId400 = Error

/**
 * @description Requested resource does not exist or is not available
 */
export type FindZoningDistrictClassByZoningDistrictClassId404 = Error

/**
 * @description Server side error
 */
export type FindZoningDistrictClassByZoningDistrictClassId500 = Error

export type FindZoningDistrictClassByZoningDistrictClassIdQuery = {
  Response: FindZoningDistrictClassByZoningDistrictClassId200
  PathParams: FindZoningDistrictClassByZoningDistrictClassIdPathParams
  Errors:
    | FindZoningDistrictClassByZoningDistrictClassId400
    | FindZoningDistrictClassByZoningDistrictClassId404
    | FindZoningDistrictClassByZoningDistrictClassId500
}

export type FindZoningDistrictClassByZoningDistrictClassIdQueryResponse = FindZoningDistrictClassByZoningDistrictClassId200
