/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from '../Error.ts'
import type { ZoningDistrictClass } from '../ZoningDistrictClass.ts'

export type FindZoningDistrictClassesByZoningDistrictIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description An object of class schemas for the zoning district.
 */
export type FindZoningDistrictClassesByZoningDistrictId200 = {
  /**
   * @type array
   */
  zoningDistrictClasses: ZoningDistrictClass[]
}

/**
 * @description Invalid client request
 */
export type FindZoningDistrictClassesByZoningDistrictId400 = Error

/**
 * @description Requested resource does not exist or is not available
 */
export type FindZoningDistrictClassesByZoningDistrictId404 = Error

/**
 * @description Server side error
 */
export type FindZoningDistrictClassesByZoningDistrictId500 = Error

export type FindZoningDistrictClassesByZoningDistrictIdQuery = {
  Response: FindZoningDistrictClassesByZoningDistrictId200
  PathParams: FindZoningDistrictClassesByZoningDistrictIdPathParams
  Errors: FindZoningDistrictClassesByZoningDistrictId400 | FindZoningDistrictClassesByZoningDistrictId404 | FindZoningDistrictClassesByZoningDistrictId500
}

export type FindZoningDistrictClassesByZoningDistrictIdQueryResponse = FindZoningDistrictClassesByZoningDistrictId200
