/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from '../Error.ts'
import type { ZoningDistrictClassCategoryColor } from '../ZoningDistrictClassCategoryColor.ts'

/**
 * @description An object containing all zoning district category colors.
 */
export type FindZoningDistrictClassCategoryColors200 = {
  /**
   * @type array
   */
  zoningDistrictClassCategoryColors: ZoningDistrictClassCategoryColor[]
}

/**
 * @description Invalid client request
 */
export type FindZoningDistrictClassCategoryColors400 = Error

/**
 * @description Server side error
 */
export type FindZoningDistrictClassCategoryColors500 = Error

export type FindZoningDistrictClassCategoryColorsQuery = {
  Response: FindZoningDistrictClassCategoryColors200
  Errors: FindZoningDistrictClassCategoryColors400 | FindZoningDistrictClassCategoryColors500
}

export type FindZoningDistrictClassCategoryColorsQueryResponse = FindZoningDistrictClassCategoryColors200
