/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import * as z from 'zod'

export const test = z.union([
  z.object({
    propertyA: z.optional(z.string()),
  }),
  z.object({
    propertyA: z.optional(z.string()),
  }),
])
