/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @type object
*/
export type OrderRequest = {
    /**
     * @type string | undefined
    */
    userId?: string;
    /**
     * @type array | undefined
    */
    productIds?: string[];
};