/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProductSchema = {
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type number | undefined
    */
    price?: number;
};