/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type OrderSchema = {
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    customerId?: string;
    /**
     * @type array | undefined
    */
    items?: string[];
};