import { resolve } from 'node:path'
import type { FileNode } from '@kubb/ast'
import type { Config, NormalizedPlugin } from '@kubb/core'
import type { BarrelType } from '../types.ts'
import { getBarrelFiles } from './getBarrelFiles.ts'

export type GeneratePerPluginBarrelParams = {
  barrelType: BarrelType
  plugin: NormalizedPlugin
  files: ReadonlyArray<FileNode>
  config: Config
}

/**
 * Generates barrel files for a single plugin's output directory.
 *
 * The barrel file is placed at `resolve(config.root, config.output.path, plugin.options.output.path)/index.ts`
 * and re-exports all files generated by that plugin, using the given `barrelType` strategy.
 *
 * Note: `plugin.options.output.path` is relative to `config.output.path`, not to `config.root`.
 * Files generated by plugins land at `config.root + config.output.path + plugin.output.path`,
 * so the barrel directory must be resolved with all three segments.
 */
export function generatePerPluginBarrel({ barrelType, plugin, files, config }: GeneratePerPluginBarrelParams): Array<FileNode> {
  const outputPath = resolve(config.root, config.output.path, plugin.options.output.path)
  return getBarrelFiles(outputPath, files, barrelType)
}
