/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const deletePetPathParamsSchema = z.object({
  petId: z.string(),
})

export const deletePet200Schema = z.array(z.enum(['TYPE1', 'TYPE2', 'TYPE3'])).describe('Successful deletion')

export const deletePetMutationResponseSchema = deletePet200Schema

export const deletePetMutationSchema = z.object({
  Response: deletePet200Schema,
  PathParams: deletePetPathParamsSchema,
  Errors: z.any(),
})
