/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description ID of the order that needs to be deleted
 * @type integer
*/
export type DeleteOrderPathOrderId = number;

/**
 * @type any
*/
export type DeleteOrderStatus400 = any;

/**
 * @type any
*/
export type DeleteOrderStatus404 = any;

/**
 * @type object
*/
export type DeleteOrderRequestConfig = {
    data?: never;
    /**
     * @type object
    */
    pathParams: {
        orderId: DeleteOrderPathOrderId;
    };
    queryParams?: never;
    headerParams?: never;
    /**
     * @type string
    */
    url: `/store/order/${string}`;
};

/**
 * @type object
*/
export type DeleteOrderResponses = {
    "400": DeleteOrderStatus400;
    "404": DeleteOrderStatus404;
};

/**
 * @description Union of all possible responses
*/
export type DeleteOrderResponse = (DeleteOrderStatus400 | DeleteOrderStatus404);