/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeletePetHeaderApiKey = string;

/**
 * @description Pet id to delete
*/
export type DeletePetPathPetId = number;

/**
 * @description Invalid pet value
*/
export type DeletePetStatus400 = any;

export type DeletePetRequestConfig = {
    data?: never;
    /**
     * @type object
    */
    pathParams: {
        petId: DeletePetPathPetId;
    };
    queryParams?: never;
    /**
     * @type object | undefined
    */
    headerParams?: {
        api_key?: DeletePetHeaderApiKey;
    };
    /**
     * @type string
    */
    url: `/pet/${string}`;
};

export type DeletePetResponses = {
    "400": DeletePetStatus400;
};

/**
 * @description Union of all possible responses
*/
export type DeletePetResponse = DeletePetStatus400;