import type { BarrelType, PluginFactoryOptions, Resolver } from '@kubb/core'

export const pluginBarrelName = 'plugin-barrel' as const

export type PluginBarrelPlugin = {
  /**
   * Plugin name as registered in `Kubb.PluginRegistry`.
   * The union with `(string & {})` preserves autocomplete for known plugin names
   * while still accepting any arbitrary string at runtime.
   */
  name: keyof Kubb.PluginRegistry | (string & {})
  /**
   * How to generate `index.ts` barrel files for this plugin's output directory.
   * - `'all'` — wildcard re-exports (`export * from`)
   * - `'named'` — named exports only
   * - `'propagate'` — propagate re-exports from nested barrel files upward
   * - `false` — disable barrel generation for this plugin
   */
  barrelType: BarrelType | false
}

export type PluginBarrelOptions = {
  /**
   * Configuration for the root barrel file (e.g. `src/gen/index.ts`).
   * When omitted no root barrel is generated by `plugin-barrel`.
   */
  root?: {
    /**
     * How to generate the root `index.ts` barrel file.
     * - `'all'` — wildcard re-exports (`export * from`)
     * - `'named'` — named exports only
     * - `false` — disable root barrel generation
     */
    barrelType: 'all' | 'named' | false
  }
  /**
   * Per-plugin barrel configuration.
   * Each entry controls whether and how an `index.ts` is created inside that plugin's output directory.
   * Plugins not listed here fall back to the `barrelType` declared in their own `output.barrelType` option.
   */
  plugins?: Array<PluginBarrelPlugin>
}

export type PluginBarrel = PluginFactoryOptions<typeof pluginBarrelName, PluginBarrelOptions, PluginBarrelOptions, Resolver>

declare global {
  namespace Kubb {
    interface PluginRegistry {
      [pluginBarrelName]: PluginBarrel
    }
  }
}
