/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Category } from './Category.ts'
import type { Tag } from './Tag.ts'

export const addPetRequestStatusEnum3 = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type AddPetRequestStatusEnum3Key = (typeof addPetRequestStatusEnum3)[keyof typeof addPetRequestStatusEnum3]

export type AddPetRequest = {
  /**
   * @type integer | undefined, int64
   */
  id?: number
  /**
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category?: Category
  /**
   * @type array
   */
  photoUrls: string[]
  /**
   * @type array | undefined
   */
  tags?: Tag[]
  /**
   * @description pet status in the store
   * @type string | undefined
   */
  status?: AddPetRequestStatusEnum3Key
}
