/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Category } from './Category.ts'
import type { Tag } from './Tag.ts'

export const petStatusEnum = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type PetStatusEnumKey = (typeof petStatusEnum)[keyof typeof petStatusEnum]

export type Pet = {
  id?: number
  name: string
  category?: Category
  photoUrls: string[]
  tags?: Tag[]
  /**
   * @description pet status in the store
   */
  status?: PetStatusEnumKey
}
