/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const petStatus = {
  Available: 'available',
  Pending: 'pending',
  Sold: 'sold',
} as const

export type PetStatusKey = (typeof petStatus)[keyof typeof petStatus]
