/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FooMapped } from "./FooMapped.ts";

export const barMappedIdEnum = {
    "bar": "bar"
} as const;

export type BarMappedIdEnumKey = (typeof barMappedIdEnum)[keyof typeof barMappedIdEnum];

export type BarMapped = ((FooMapped & {
    id: "bar";
}) & {
    /**
     * @type string | undefined
    */
    bar?: string;
    id: BarMappedIdEnumKey;
});