/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CardPaymentUnion = {
    /**
     * @type string | undefined
    */
    type?: string;
    /**
     * @type string | undefined
    */
    cardNumber?: string;
};