/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaymentMethodUnion } from "./PaymentMethodUnion.ts";

export type ExtendedPaymentMethodUnion = PaymentMethodUnion;