/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const fooMappedIdEnum = {
    "bar": "bar",
    "baz": "baz"
} as const;

export type FooMappedIdEnumKey = (typeof fooMappedIdEnum)[keyof typeof fooMappedIdEnum];

export type FooMapped = {
    /**
     * @type string
    */
    id: FooMappedIdEnumKey;
};