/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BarUnion } from "./BarUnion.ts";
import type { BazUnion } from "./BazUnion.ts";

export type FooUnion = (BarUnion | BazUnion);