/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaymentMethod } from "./PaymentMethod.ts";

export type WalletPayment = (PaymentMethod & {
    walletId?: string;
});