/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaymentMethodMapped } from "./PaymentMethodMapped.ts";

export type WalletPaymentMapped = (PaymentMethodMapped & {
    walletId?: string;
});