/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * CatDogWithoutMapping
 */
export type catDogWithoutMapping =
  | (cat & {
      type: 'Cat'
    })
  | (dog & {
      type: 'Dog'
    })
