/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type catDogDiscriminatorWithoutMapping =
  | (catDogDiscriminatorWithoutMapping & {
      type: 'Cat'
    })
  | (catDogDiscriminatorWithoutMapping & {
      type: 'Dog'
    })
