/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type catDogDiscriminator =
  | (catDogDiscriminator & {
      type: 'Cat'
    })
  | (catDogDiscriminator & {
      type: 'Dog'
    })
  | (catDogDiscriminator & {
      type: 'Bulldog'
    })
