/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * CatDog
 */
export type catDog =
  | (cat & {
      type: 'Cat'
    })
  | (dog & {
      type: 'Dog'
    })
  | (dog & {
      type: 'Bulldog'
    })
