/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Null response
 */
export type CreatePetWithEmptySchemaTypeUnknown = createPetWithEmptySchemaTypeUnknown & {
  /**
   * @type object | undefined
   */
  name?: createPetWithEmptySchemaTypeUnknown
  /**
   * @type string
   */
  message: string
}

export type createPetWithEmptySchemaTypeUnknownMutation = {
  Response: createPetWithEmptySchemaTypeUnknown | createPetWithEmptySchemaTypeUnknown
  Request: createPetWithEmptySchemaTypeUnknown
  Errors: any
}
