/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Null response
 */
export type CreatePetsStatus201 = error & {
  /**
   * @type object | undefined
   */
  name?: errorCode
  /**
   * @type string
   */
  message: string
}

/**
 * @description Accepted response
 */
export type CreatePetsStatus202 = void

/**
 * @description unexpected error
 */
export type CreatePetsStatusError = error

export type CreatePetsRequestData = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  tag: string
}

export type CreatePetsResponses = {
  '201': CreatePetsStatus201
  '202': CreatePetsStatus202
}

export type CreatePetsResponseData = CreatePetsResponses[keyof CreatePetsResponses]
