/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Null response
 */
export type CreatePets201 = Error & {
  /**
   * @type object | undefined
   */
  name?: ErrorCode
  /**
   * @type string
   */
  message: string
}

/**
 * @description Accepted response
 */
export type CreatePets202 = unknown

/**
 * @description unexpected error
 */
export type CreatePetsError = Error

export type CreatePetsMutationRequest = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  tag: string
}

export type CreatePetsMutationResponse = CreatePets201 | CreatePets202

export type createPetsMutation = {
  Response: createPets201 | createPets202
  Request: createPetsMutationRequest
  Errors: any
}
