/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const vehicleTypeEnum = {
  car: 'car',
} as const

export type VehicleTypeEnumKey = (typeof vehicleTypeEnum)[keyof typeof vehicleTypeEnum]

export type vehicle = car & {
  /**
   * @type string
   */
  type: VehicleTypeEnumKey
}
