/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type cat = {
  /**
   * @type string
   */
  type: string
  /**
   * @type string | undefined
   */
  name?: string
}
