/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type dog = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  type: 'Dog'
  /**
   * @type number | undefined
   */
  bark?: number
}
