/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const enumItemsEnum = {
  created_at: 'created_at',
  description: 'description',
} as const

export type EnumItemsEnumKey = (typeof enumItemsEnum)[keyof typeof enumItemsEnum]

export type enumItems = EnumItemsEnumKey[]
