/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const enumNullableMemberEnum = {
  first: 'first',
  second: 'second',
} as const

export type EnumNullableMemberEnum = (typeof enumNullableMemberEnum)[keyof typeof enumNullableMemberEnum]

export type enumNullableMember = EnumNullableMemberEnum | null
