/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const enumNullableTypeEnum = {
  first: 'first',
  second: 'second',
} as const

export type EnumNullableTypeKey = (typeof enumNullableTypeEnum)[keyof typeof enumNullableTypeEnum]

export type enumNullableType = EnumNullableTypeKey | null
