/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const EnumNamesTypeEnum = {
  Pending: 0,
  Received: 1,
} as const

export type EnumNamesTypeEnum = (typeof EnumNamesTypeEnum)[keyof typeof EnumNamesTypeEnum]

export type enumNamesType = EnumNamesTypeEnum
