/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const enumArrayIdentifierEnum = {
  NW: 'NW',
  NE: 'NE',
  SW: 'SW',
  SE: 'SE',
} as const

export type EnumArrayIdentifierEnum = (typeof enumArrayIdentifierEnum)[keyof typeof enumArrayIdentifierEnum]

export type enumArray = {
  /**
   * @type array | undefined
   */
  identifier?: [number, string, EnumArrayIdentifierEnum, ...unknown[]]
}
