/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FooBasetypeEnum = 'type-string' | 'type-number'

export type FooBase = {
  /**
   * @type string
   */
  $type: FooBasetypeEnum
}
