/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description This probably should fail miserably
 */
export type mixedValueTypeConst = {
  /**
   * @type number | undefined
   */
  foobar?: 'foobar'
}
