/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type paymentAccountDetailsResponse =
  | (ACHDetailsResponse & {
      type: 'ACH'
    })
  | (domesticWireDetailsResponse & {
      type: 'DOMESTIC_WIRE'
    })
