/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */
import type { pet } from '../petDict'

export type PetDict = {
  /**
   * @type object
   */
  matrix: {
    [key: string]: pet
  }
}
