/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type petsStoreNotifcationDiscriminator = (
  | (petsStoreNotifcationDiscriminator & {
      notificationType: 'DOCUMENT_DISAPPROVED'
    })
  | (petsStoreNotifcationDiscriminator & {
      notificationType: 'DOCUMENT_APPROVED'
    })
) & {
  /**
   * @type integer
   */
  id: number
  /**
   * @type string, date-time
   */
  createdAt: string
  /**
   * @type boolean
   */
  isSeen: boolean
}
