/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type readOnly = {
  /**
   * @type integer | undefined
   */
  readonly attribute_readonly?: number
  /**
   * @description not required
   * @type integer | undefined
   */
  attribute_writeOnly?: number
  /**
   * @type integer | undefined
   */
  readonly attribute_with_ref?: readOnly
  /**
   * @description not required
   * @type integer | undefined
   */
  attribute_with_ref_readonly?: readOnly
}
