/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type string
 */
export type ShowPetByIdPathPetId = string

/**
 * @type object
 */
export type ShowPetByIdStatus200 = object

/**
 * @type object
 */
export type ShowPetByIdStatusDefault = object

/**
 * @type object
 */
export type ShowPetByIdRequestConfig = {
  data?: never
  /**
   * @type object
   */
  pathParams: {
    petId: ShowPetByIdPathPetId
  }
  queryParams?: never
  headerParams?: never
  /**
   * @type string
   */
  url: `/pets/${string}`
}

/**
 * @type object
 */
export type ShowPetByIdResponses = {
  '200': ShowPetByIdStatus200
  default: ShowPetByIdStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type ShowPetByIdResponse = ShowPetByIdStatus200 | ShowPetByIdStatusDefault
