/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ShowPetByIdPathPetId = string

/**
 * @description Expected response
 */
export type ShowPetByIdStatus200 = object

/**
 * @description Unexpected error
 */
export type ShowPetByIdStatusDefault = object

export type ShowPetByIdRequestConfig = {
  data?: never
  /**
   * @type {object}
   */
  pathParams: {
    petId: ShowPetByIdPathPetId
  }
  queryParams?: never
  headerParams?: never
  /**
   * @type {string}
   */
  url: `/pets/${string}`
}

export type ShowPetByIdResponses = {
  '200': ShowPetByIdStatus200
  default: ShowPetByIdStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type ShowPetByIdResponse = ShowPetByIdStatus200 | ShowPetByIdStatusDefault
