name: Format Changeset PR

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'
      - '.changeset/**'

permissions: {}

jobs:
  format:
    name: Format and Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Tools
        uses: kubb-labs/config/.github/setup@8508e66e6014b9ca1416591bc20791027b6ccf5c # main
        with:
          node-version: '22'

      - name: Format
        run: pnpm run format

      - name: Lint Fix
        run: pnpm run lint:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: 'chore: format and lint fixes'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
