/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdatePetPathPetId = string

export type UpdatePetQueryIncludeDeleted = boolean

export type UpdatePetQueryRequestSource = string

/**
 * @description Success
 */
export type UpdatePetStatus200 = object

export type UpdatePetData = {
  name: string
}

export type UpdatePetRequestConfig = {
  data?: UpdatePetData
  pathParams: {
    petId: UpdatePetPathPetId
  }
  queryParams?: {
    includeDeleted?: UpdatePetQueryIncludeDeleted
    requestSource?: UpdatePetQueryRequestSource
  }
  headerParams?: never
  url: `/pets/${string}`
}

export type UpdatePetResponses = {
  '200': UpdatePetStatus200
}

/**
 * @description Union of all possible responses
 */
export type UpdatePetResponse = UpdatePetStatus200
