/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from '../User.ts'

/**
 * @description successful operation
 */
export type CreateUserStatusDefault = User

/**
 * @description Created user object
 */
export type CreateUserData = User

export type CreateUserRequestConfig = {
  data?: CreateUserData
  /**
   * @type never | undefined
   */
  pathParams?: never
  /**
   * @type never | undefined
   */
  queryParams?: never
  /**
   * @type never | undefined
   */
  headerParams?: never
  /**
   * @type string
   */
  url: '/user'
}

export type CreateUserResponses = {
  default: CreateUserStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type CreateUserResponse = CreateUserStatusDefault
