/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from '../User.ts'

/**
 * @description The name that needs to be fetched. Use user1 for testing.
 * @type string
 */
export type GetUserByNamePathUsername = string

/**
 * @type object
 */
export type GetUserByNameStatus200 = User

/**
 * @type any
 */
export type GetUserByNameStatus400 = any

/**
 * @type any
 */
export type GetUserByNameStatus404 = any

/**
 * @type object
 */
export type GetUserByNameRequestConfig = {
  data?: never
  /**
   * @type object
   */
  pathParams: {
    username: GetUserByNamePathUsername
  }
  queryParams?: never
  headerParams?: never
  /**
   * @type string
   */
  url: `/user/${string}`
}

/**
 * @type object
 */
export type GetUserByNameResponses = {
  '200': GetUserByNameStatus200
  '400': GetUserByNameStatus400
  '404': GetUserByNameStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetUserByNameResponse = GetUserByNameStatus200 | GetUserByNameStatus400 | GetUserByNameStatus404
