/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description successful operation
 */
export type LogoutUserStatusDefault = any

export type LogoutUserRequestConfig = {
  /**
   * @type never | undefined
   */
  data?: never
  /**
   * @type never | undefined
   */
  pathParams?: never
  /**
   * @type never | undefined
   */
  queryParams?: never
  /**
   * @type never | undefined
   */
  headerParams?: never
  /**
   * @type string
   */
  url: '/user/logout'
}

export type LogoutUserResponses = {
  default: LogoutUserStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type LogoutUserResponse = LogoutUserStatusDefault
