/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'
import { apiResponseSchema } from './apiResponseSchema.ts'

export const uploadFilePathParamsSchema = z.object({
  petId: z.int(),
})

export const uploadFileQueryParamsSchema = z.optional(
  z.object({
    additionalMetadata: z.optional(z.string()),
  }),
)

/**
 * @description successful operation
 */
export const uploadFile200Schema = apiResponseSchema

export const uploadFileMutationRequestSchema = z.optional(z.instanceof(File))

export const uploadFileMutationResponseSchema = uploadFile200Schema

export const uploadFileMutationSchema = z.object({
  Response: uploadFile200Schema,
  Request: uploadFileMutationRequestSchema,
  QueryParams: uploadFileQueryParamsSchema,
  PathParams: uploadFilePathParamsSchema,
  Errors: z.any(),
})
